### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by grootersluiz** [kyriosdata/oo#102]
Visto que OO é apenas uma perspectiva utilizada no momento de programar, as vantagens da linguagem C++ em relação à linguagem C são: praticidade, velocidade, ferramentas que proporcionam agilidade e mais possibilidades de otimização do software. Essas vantagens existem porque a linguagem C++ é uma versão mais moderna da linguagem C, que foi desenvolvida justamente para trazer mais "poder de desenvolvimento".

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
