### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by valeriateles** [kyriosdata/oo#104]
A Orientação a objeto é uma forma de ver e extrair do universo as partes necessárias, de forma a se registrar problemas e desenvolver soluções. A OO ao contrário da linguagem estruturada ( ex.: C) permite de forma mais fácil programar algo mais complexo, mesmo que nem sempre seja mais eficiente. 
A linguagem C++ seria uma intermediária entre a linguagem de baixo e alto nível, podendo ser tanto estruturada quanto OO, contudo quando utilizada de forma OO oferece inúmeras implementações que muitas vezes auxiliam o programador na otimização de seu tempo, além do que em alguns casos pode ser mais confiável na hora de fazer alterações e implementações em programas.
O programador quem escolhe qual a linguagem vai usar se baseando no que precisa programar, sendo assim algumas vezes os programas em OO podem ser bem mais rápidos de serem escritos que em C. Em outros casos os em C podem ser mais eficientes em questões de otimização.
(foi um pouco do que eu entendi).

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
Contudo um código em C++ pode resultar em maior tempo de execução do que um código equivalente em C. Isso ocorre pois algumas implementações OO são mais custosas para processamento (por exemplo, a implementação do polimorfismo).
COM APROVEITAMENTO.
