### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by valeriateles** [kyriosdata/oo#106]
i. Mesmo que um sistema ainda não exista para ser decomposto, sabemos que a OO trabalha com partes extraídas de um determinado universo, e ao ver esse universo já se deve planejar as partes e suas comunicações. Por isso no planejamento desse sistema já deve ser feita a analise de seus requisitos. O que e como ele deve fazer e a partir do que ele deve ser ativado. Por mais que o programa não tenha sido escrito e o sistema não esteja pronto ele já deve estar bem planejado para se iniciar sua escrita, estruturação e design.
ii.  o instrumento empregado para documentar a estrutura de um software, conforme a ementa, é o UML - Unified Modelling Language, é uma linguagem de modelagem que permite apresentar o sistema de forma padronizada, facilitando sua compreensão.
iii. Os artigos fazem menção a já ter uma estruturação do sistema, do seu comportamento, funcionamento e funcionalidade antes mesmo de ter sido criado, escrito ou implementado. É como se houvesse todo um planejamento já esboçado e analisado antes de começar a escrever o sistema. Ele não precisará ser escrito para depois modulado, ele já pode ser pensado em módulos( partes menores, dependentes ou independentes de outras) e em suas formas de comunicação (interação entre partes).

**Comment by kyriosdata** [comment]
Apenas uma observação sobre o iii. Orientação a Objetos é uma estratégia para "se ver" um software. Naturalmente, quando se emprega OO, ele está sendo dividido, fragmentado, modularizado. Isto, neste caso, é feito via os conceitos de orientação a objetos. 

Muito bom! COM APROVEITAMENTO. 👍
