### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by samirmont0** [kyriosdata/oo#107]
Tendo em vista que C++ é uma extensão de C, ele traz mais modernidade, fazendo com que o desenvolvimento do software seja mais flexível de uma maneira geral, e por ter a capacidade de ser orientado a objetos, pode-se dizer que ele tem uma ferramenta a mais, e isso pode fazer com que o código seja escrito de forma mais ágil e o produto final tem uma confiabilidade maior, além de ser reutilizável. E pelo fato de os elementos OO serem imitadores do que existe no mundo, isso da uma visão melhor do que realmente ta sendo proposto. Porém fica a critério do programador qual ferramenta ele vai usar no projeto.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
