### ISSUE TITLE
Meu Repositório

### ISSUE THREAD

**Issue by AlvesMarina** [kyriosdata/oo#11]
- Meu nome: Marina Pereira Alves

- Meu registro acadêmico: 201910896

- Minha conta no Github: https://github.com/AlvesMarina

**Comment by kyriosdata** [comment]
Marina, não localizamos o repositório conforme pede a atividade. Verifique, por favor.

**Comment by AlvesMarina** [comment]
Boa noite, professor!
Segue link com o repositório: https://github.com/AlvesMarina/poo-2020-01

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
