### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by lucabenetti** [kyriosdata/oo#110]
OO aproxima o mundo real ao código e o código ao mundo real. Em C, por meio do código estruturado, podemos obter o mesmo resultado desejado (saída) de que em um programa C++. Entretanto, ficamos muito dependentes da sintaxe estruturada e do código, quando o que derivou o início de nosso desenvolvimento foi um cenário real. OO facilita o entendimento, a interpretação pois trás ao desenvolvedor a semelhança do objeto presente no código com o objeto presente no mundo real, o que se traduz em uma maior capacidade de interpretação, abstração, manutenção e possibilidades de uma aplicação.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
