### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by felipekafuri** [kyriosdata/oo#111]
A questão é, que existem niveis de abstração e cada linguagem possui seu nivel de abstração. Quanto maior o nivel de abstração menos o programador ve o que acontence por debaixo dos panos como uma alocação de memoria por exemplo, isso parece tornar as coisas mais faceis e por um lado realmente torna, entretanto, nada vem graça, a partir do momento que o programador ganha o poder de se preocupar menos com o coódigo de mais baixo nivel ele obrigatoriamente deve se preocupar com questões como organização e arquitetura do seu software e no meu ver é ai que entra a mágica do OO, a mágica de ver atraves das oticas do OOP. Creio que essa seja a diferença que vc ganha programando em C++ ao inves de C, apesar de o nivel de abstraçao de uma pra outra n ser um abismo, o pouco que se ganha ja auxilia.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
