### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by pavaladao** [kyriosdata/oo#113]
O que se ganha com um código C++ em relação ao código em C é algo puramente estrutural, que pode dar mais velocidade de desenvolvimento para o projeto, dependendo se a linguagem orientada a objetos for a melhor ferramenta para tal. A lógica de programação em si é a mesma nos dois paradigmas, porém a forma como se enxerga a estruturação e o relacionamento entre os dados e os comandos é completamente diferente. Porém diferente não significa melhor. No caso, devemos estudar a intenção e a complexidade do projeto para sabermos se desenvolver em C++ é mais adequado que em C ou não, se vai facilitar o desenvolvimento ou não.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
