### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by mantisoficial** [kyriosdata/oo#114]
i. O título do artigo e seu conteúdo sugerem que, mesmo que um novo sistema ainda não exista, ele já deve ser planejando em partes (módulos) pois há muitas vantagens como gerenciamento, flexibilidade do produto e compreensão, garantindo assim mais qualidade ao sistema.
ii.  Na nossa disciplina o instrumento empregado para documentar a estrutura de um software é o UML (Unified Modelling Language). É uma linguagem de modelagem que nos permite apresentar e planejar o sistema de forma padronizada e de fácil compreensão.
iii. Pode-se perceber um forte ligação entre os artigos e a orientação a objetos. Os artigos são relacionados a modularização e decomposição de sistemas, elementos muito presentes na OO para facilitar o gerenciamento e a reutilização do código.

**Comment by kyriosdata** [comment]
Muito bom! COM APROVEITAMENTO. 👍
