### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by MatheusBorgez** [kyriosdata/oo#116]
Ao se criar uma estrutura orientada a objetos bem arquitetada, os ganhos são diversos. Entre eles podemos listar: 

**1** - Reutilização de código, tornando tanto o entendimento, quanto a expansão do sistema muito mais simples.

**2** - Distribuição de responsabilidades, tornando o código mais simples, performático e duradouro.

**3** - Universalização, a OO permite a existência de ferramentas como UML, tornando assim, um diagrama entendível para programadores de diferentes linguagens, desde que os mesmos compreendam como funciona uma estrutura OO e entendam sintaxe UML.

**4** - Longevidade, um software OO bem planejado tende a durar infinitamente mais, mesmo que os requisitos, desenvolvedores ou tecnologias mudem. Independente destes elementos a estrutura OO permanece a mesma, tornando a vida útil do software exponencialmente maior.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
