### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by sarahgalves** [kyriosdata/oo#117]
Qualquer linguagem de programação pode executar qualquer coisa. A diferença é o nível de abstração fornecida para construir códigos dentro de determinados padrões. De certa modo, OO é apenas uma forma abstrata. Tudo pode ser aplicado em qualquer linguagem, a diferença é que algumas facilitam o trabalho. Na frase "OO é uma espécie de "óculos" e quando se olha por um óculos vê-se o que já existe" evidencia-se OO é uma forma de ver e registrar algo do interesse empregando classes, relacionamentos entre elas, objetos e outros. Ou seja, essa relação se torna mais fácil em C++.
Em C você deve escrever códigos para lidar com tudo o que outras linguagens fazem em sua estrutura básica. O código fica bagunçado, extenso, confuso e feio. Além disso, a maioria dos erros provavelmente só serão percebidos quando forem execução. Ainda é possível mencionar o fato do desenvolvimento ser mais lento, também envolve muito trabalho manual e pode causar mais problemas.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
