### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by im-pokz** [kyriosdata/oo#120]
O C++, em geral, é uma linguagem mais flexível em comparação ao C. Por ser uma linguagem OO, ela possui muito mais recursos e possibilidades para os programadores. Existem várias características que contribuem para essa simplicidade maior do C++. Uma delas é a criação de **Classe**, onde é possível atribuir várias variáveis e características dentro de um objeto só, sem a necessidade de criar inúmeras strings ou vetores, como seria na linguagem C. Outras características seriam a **Abstração** e o **Encapsulamento**, onde é possível dividir os problemas em áreas menores do código e executá-los individualmente, tornando mais fácil a identificação de erros e bugs, o que ajuda na compilação e debbuging do código, além disso, o programador não precisa ter um conhecimento TÃO profundo da linguagem. Na linguagem C isso não é possível, o código deve ser executado sempre por inteiro, que dificulta muito o desenvolvedor em encontrar problemas no algoritmo. Por último e não menos importante, a **Herança**. Com ela é possível compartilhar atributos e métodos entre várias classe durante o código com muita facilidade, dessa forma, não é necessário escrever a mesma coisa várias vezes no mesmo código. Em resumo, o código em C é muito maior, mais complexo e mais feio do que o código em C++.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
