### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by andrey-dias** [kyriosdata/oo#121]
Levando em consideração que em minha visão OO não está limitado somente à programação, assim como presente no texto, é uma forma de "enxergar o mundo", enquanto na linguagem C temos uma linguagem cujo paradigma procedural desenvolve o código de maneira à otimizar memória com o uso de funções e sub-rotinas, existe também o C++ que utiliza o paradigma OO para organizar melhor o código em classes e proporcionar boas práticas dentro da engenharia de requisitos ao modelar um sistema em UML por exemplo pela ótica da orientação a objetos. Então acredito que cada sistema tenha a necessidade do uso de determinado paradigma, a vantagem da orientação a objetos está na organização e manutenção do código e novamente, em um dos processos de criação de um sistema em sua modelagem UML.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
