### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by SleepyDarlin** [kyriosdata/oo#124]
A partir da leitura dos conteúdos propostos, podemos concluir que OO se diferencia da tradicional programação procedural por ser uma nova maneira de interpretar os mesmos problemas, ganha-se, então, mais ferramentas para que o programador possa escolher qual a melhor forma de resolver tais problemas.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
