### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by Thyago-C** [kyriosdata/oo#126]
A orientação a objetos é mais do que apenas uma ferramenta qualquer a ser utilizada. A orientação a objetos é uma forma de perceber o mundo ao nosso redor. Quando esse paradigma de programação foi criado, o objetivo era alcançar a simplicidade e a naturalidade com a qual uma máquina poderia se comunicar com o ambiente a sua volta.
Apesar de que algumas coisas podem ser criadas utilizando o paradigma estruturado, a orientação a objetos é um paradigma com diversos benefícios para quem o utiliza. Alguns dos benefícios são: Naturalidade do código, reaproveitamento, fácil manutenção, maior segurança, dentre outros. Tudo isso se deve ao fato de que o programa é construído por meio do conceito de objetos, que separa partes do programa mas que permite que essas partes se comuniquem. Portanto, é possível fazer uma melhoria em um objeto e beneficiar a todas as partes que utilizam o objeto melhorado.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
