### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by atilaufg** [kyriosdata/oo#128]
Tendo em vista que a orientação a objetos (OO) é uma ferramenta criada para atingir a simplificação da programação modular e focar nos objetivos e informações que o usuário almeja, deixando um pouco de lado a lógica estruturada e rígida de linguagens não OO; e que há linguagens inteiramente baseadas na OO, como Java, não torna-se impossível converter algo não OO para algo OO. Uma vez que temos toda uma estrutura já programada em OO, usando de exemplo a linguagem C++, a conversão pode ser feita de forma a usar e analisar a lógica estrutural desta estrutura em OO e reproduzi-la em uma linguagem não OO, como exemplo a linguagem C.
 Mesmo a linguagem C não tendo artifícios para orientação a objetos, não quer dizer que não se possa fazer, será mais burocrático e repetitivo. Programar em C++ orientado a objetos facilita a vida do programador. Temos de exemplo um programa em C 'orientado a objetos' o GTK Project, que usa a ''livraria'' GObject em C.

**Comment by atilaufg** [comment]
Achei um pouco confuso minha explicação, mas resumidamente podemos reproduzir um código não orientado a objetos na linguagem C (por exemplo) que foi programado orientado a objetos na linguagem C++, analisando e reproduzindo-o de forma lógica em todas as etapas.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
