### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by guilhermefaleiros** [kyriosdata/oo#129]
Podemos concluir que a Orientação a Objetos é uma tentativa de aproximação do software ao mundo real, de modo que elementos do mundo real possam ser representados com maior fidelidade. Uma das grandes vantagem é que a tradução das regras de negócio em um determinado software se torna bem mais natural quando usados conceitos de OO, além disso, conceitos de modularização ajudam bastante na organização e arquitetura da aplicação, tornando-se algo bem mais escalável e de fácil manutenção, já que, hoje em dia se preza muito mais por um código claro e limpo do que necessariamente performático. Assim, essa é a grande vantagem de utilizar POO (C++) em relação a linguagens não orientadas a objeto (C).

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
