### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by driellyg** [kyriosdata/oo#132]
Como dito no trecho publicado pelo professor, a conversão de algo dito OO para algo que não é OO obtendo os mesmos resultados se torna possível pois OO é uma maneira de ver as coisas. Não existe somente uma forma, podendo sim chegar aos mesmos resultados seguindo outros caminhos. 
Em relação a conversão para código C++ e seu suposto ganho em relação ao código C, me lembro do professor comentar sobre OO tornar problemas complexos mais simples, mas não necessidade de utilizar quando se trata de um problema simples, seria criar uma grande solução para um pequeno problema. O ganho em C++ utilizando OO para um grande problema é a quebra daquele problema em tópicos menores, e sendo resolvido em etapas menores. Na ferramenta indicada pelo professor temos um compilador para C e C++, e como em tantos outros, podemos ver que em ambas linguagens podemos ter ganhos, mas tudo depende da forma de se olhar para o problema e sua complexidade.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
