### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by giancarlobara** [kyriosdata/oo#135]
A programação estruturada deixa muito a desejar em relação a programação OO. São inúmeras vantagens que a OO traz, entre elas podemos citar a maior facilidade na manutenabilidade do software, pois como ela é dividida em várias classes, facilita a identificação de problemas no código. Outra vantagem é o reaproveitamento do código, que também utilizando as classes, podemos ter parte do software já concluído.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
