### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by rafssn** [kyriosdata/oo#137]
Podemos afirmar que OO é uma forma de otimizar processos de um software, uma maneira de aproximar a complexidade de um código ao mundo real. Ao utilizar os princípios de OO como uma lente, mesmo que paralelamente se consiga criar os mesmos mecanismos sem utilizar OO, obtemos muitas mais vantagens em processos específicos e boas práticas da programação moderna, como a maximização do reaproveitamento de códigos, a facilidade e otimização do processo de manutenção, melhorias na organização, modularização e arquitetura de um projeto, o isolamento de regras em classes e também a legibilidade aprimorada em grandes projetos. Dessa forma, essas são grandes vantagens de se usar POO.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
