### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by jeferson1f** [kyriosdata/oo#138]
Gostaria de saber se existe um livro que seja **a referência** para alguém que não teve contato anterior com OO para ter melhor noção dos conceitos e forma de pensar OO.

**Comment by plinioleitao** [comment]
Favor ver bibliografia mencionada no plano da disciplina:
https://github.com/kyriosdata/oo/blob/master/media/plano-poo.pdf
COM APROVEITAMENTO.
