### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by jeferson1f** [kyriosdata/oo#139]
O fato do código funcionar em ambas as linguagens só quer mostrar que existe reusabilidade de código entre as duas, mas se for observada a forma de organização e visualização do problema a ser resolvido como código, a visão de OO do C++ é muito mais clara e organizada. Com a orientação a objetos, é possível (nativamente) o encapsulamento, a hierarquização, uso de classes e o polimorfismo, o que torna código mais amigável para ser construído, melhor estruturado e com melhor reutilização e fácil incremento e/ou manutenção.

Assim sendo, o código pode não funcionar diferente, mas sua estrutura será melhor, mais organizada e o design do software será melhor construído.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
