### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by alisson-b** [kyriosdata/oo#142]
A utilização de um linguagem de programação orientada a objetos (C++) pode favorecer a visualização e resolução de problemas mais complexos, em relação à linguagem de programação estruturada (C). Dessa forma, a linguagem C++ pode ser mais adequada para o registro de um escopo, do que a linguagem C. Além disso, apesar de a linguagem C geralmente possuir desempenho superior a um mesmo algoritmo desenvolvido em C++, a manutenção e reutilização de códigos em OO é mais vantajosa e facilitada para um desenvolvedor.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
