### ISSUE TITLE
"Reflexão"

### ISSUE THREAD

**Issue by taynasantana** [kyriosdata/oo#143]
São varias as vantagens da POO, como a simplificação de um código genérico , a eliminação de repetição , deixando o código mais consistente , tornando mais fácil fazer a manutenção e evolução do código.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
