### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by pablofurtado** [kyriosdata/oo#144]
A conversão de um código em C++ para C é sim viável em determinados casos, porém, em sua maioria são os casos com problemas simples sem uma grande complexidade, o que o torna cada vez mais desvantajoso á medida que a complexidade cresce, já que o objetivo da OO é uma melhor visualização e organização dos dados e informações de códigos complexos. Essa forma mais dinâmica e estruturada para permitir uma visão mais ampla do escopo e de como os elementos funcionam considerando principalmente suas relações entre si torna muito mais rápido, simples, agradável e maleável possíveis alterações e análises futuras a serem feitas nesse código.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
