### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by mantisoficial** [kyriosdata/oo#146]
i. Objeto "Iphone" da classe "Smartphone";
Objeto "Caneta Sharpie Ponta Fina" da classe "Caneta Permanente";
Objeto "Óculos Preto de Grau" da classe "Óculos".

ii. Objeto "Porta Branca" da classe "Porta";
Objeto "Janela Circular " da classe "Janela";
Objeto "Janela Quadrada" da classe "Janela".

iii. Objeto "Uniforme de Futebol" da classe "Uniforme";
Objeto "Jogador de Futebol" da classe "Esportista";
Objeto "Anúncio da Mastercard" da classe "Anúncio".

**Comment by kyriosdata** [comment]
Muito bom, em particular o "Anúncio". Esta é a percepção que devemos ter quando observamos algo na perspectiva orientada a objetos. Há sutilezas, e elas podem ser fundamentais para a modelagem em questão.

COM APROVEITAMENTO. 👍
