### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by AlvesMarina** [kyriosdata/oo#148]
1. 
- Categoria Eletrônicos: Celular, Notebook, Tablet.
- Categoria Escrever: Canetas, lápis e caderno.
- Categoria Vestimenta: Camisa SVPERBIA.
2. 
- Categoria Ventilação: janelas.
- Categoria Telhado: telhas.
- Categoria Entrada/Saída: Porta.
3. 
- Categoria Jornalistas: As pessoas com microfones e câmeras atrás do gol.
- Categoria Jogadores: Pessoa dentro do campo.
- Categoria Torcedores: Pessoa da arquibancada.

**Comment by kyriosdata** [comment]
Algumas observações. O singular quase sempre é empregado. Ou seja, "Eletrônico" em vez de "Eletrônicos". Em tempo, "Eletrônico" é uma categoria ou classe ampla, não está errado. 

- **Escrever** é um verbo, é ação. É mais natural usar "Escrita", substantivos. Eu diria que Caneta, lápis e caderno estão associados a escrita, mas canetas e lápis em grupo distinto de caderno. De fato, talvez até caneta em grupo distinto de lápis.

- **Ventilação**. Fantástico! Inspirado por janela. Significa que você é capaz de perceber "além do que vê". Eu diria que é mais abstrato do que simplesmente Janela. E esta sensibilidade é muito importante para a modelagem OO.  O mesmo ocorre com "Entrada/saíde" e Porta.

- **Telhado** e **Telha** são distintos. Um é formado por uma agregação (veremos mais adiante), do outro. 

- As demais classes, apenas para deixar clara a importância do singular: Jornalista, Jogador, Torcedor. Há uma infinidade de instâncias destas classes na figura. 

Muito bom. COM APROVEITAMENTO. 👍
