### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by lucabenetti** [kyriosdata/oo#150]
i.	"Lápis preto" da classe "Lápis".
	"Ipad preto" da classe "Tablet".
	"Camiseta verde" da classe "Camiseta".

ii.	"Porta branca" da classe "Porta".
	"Janela branca retangular" da classe "Janela".
	"Chaminé marrom retangular" da classe "Chaminé".
	
iii.	"Goleiro" da classe "Jogador".
	"Bandeirinha" de impedimento da classe "Bandeira".
	"Grama" esmeralda da classe "Grama".

**Comment by kyriosdata** [comment]
Apenas algumas observações. A bandeirinha de impedimento eu não consegui ver, tudo bem. Se era a bandeira empregada para marcar os quatro cantos do campo, talvez, conforme o próprio nome indica, estaria mais para Marcação, como a marca do pênalti, por exemplo, do que bandeira. 

Muito bom. COM APROVEITAMENTO. 👍
