### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by AlvesMarina** [kyriosdata/oo#151]
1. Eu interpreto o título do artigo sendo como "dicas" para melhor separar um sistemas em módulos, quais critérios usar e como usá-los. O título sugere uma estratégia de desenvolvimento de software que é a separação do código em partes ou módulos; não pensar nele como um todo a ser construído, mas sim em pequenas partes que juntas formam o sistema, a fim de otimizar o sistema e o tempo e gerar praticidade para o desenvolvedor.

2. De acordo com a ementa, o instrumento que usamos para documentar a estrutura de um software é o UML (Unified Modeling Language). O UML ajuda a modelar e documentar códigos na forma orientada à objetos.

3. Há bastante relação entre os artigos e OO. Os artigos sugerem métodos e critérios para separar um sistema em módulos, e informam quais os benefícios disso, essa estratégia é bastante utilizada em OO, já que OO sugere uma maneira de pensar no código de forma não estruturada, mas sim dividindo-o em partes.

**Comment by kyriosdata** [comment]
Muito bom! COM APROVEITAMENTO. 👍
