### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by lucabenetti** [kyriosdata/oo#153]
i. O título sugere que já no processo de modelagem do sistema, haja um cuidado especial quanto a classificação e separação de responsabilidades. Este processo de modularização é um dos principais critérios que irão garantir a longa vida do sistema, pois os problemas são fragmentados em problemas menores, tornando mais fácil a compreensão e trabalho isolado em determinado módulo. 

ii. Na nossa disciplina, o instrumento empregado para documentar a estrutura de um software será o UML (Unified Modelling Language). Tal ferramenta permite estruturar projetos de software de maneira padronizada, facilitando a compreensão.

iii. Sim. A decomposição é inerente no desenvolvimento em OO, pela possibilidade de classificação dos objetos e sua esperada responsabilidade única. A importância do design e correta separação do módulos permite o encapsulamento (outro conceito recorrente em OO) no desenvolvimento. A necessidade da documentação da estrutura (representando as classes e relações de OO em UML) do projeto aliada a modularização permite a mais fácil compreensão e manutenção do sistema.

**Comment by kyriosdata** [comment]
Muito bom. COM APROVEITAMENTO. 👍
