### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by rafssn** [kyriosdata/oo#154]
1. Objeto "Óculos Preto" da classe "Óculos".
Objeto "MacBook" da classe "Notebook".
Objeto "Camiseta verde SVPERBIA" da classe "Camiseta".

2. Objeto "Janela quadriculada" da classe "Janela".
Objeto "Janela circular" da classe "Janela".
Objeto "Porta branca" da classe "Porta".

3. Objeto "Zagueiro" da classe "Jogador".
Objeto "Arquibancada superior" da classe "Arquibancada".
Objeto "Bandeira Reino Unido" da classe "Bandeira".

**Comment by kyriosdata** [comment]
É isso! COM APROVEITAMENTO. 👍
