### ISSUE TITLE
Problemas de saúde e continuidade das atividades

### ISSUE THREAD

**Issue by MMHIT** [kyriosdata/oo#157]
Prezado Professor, Bom Dia!
Sou o aluno Paulo Victor Moreira Matheus, da turma de Poo
nesta sexta dia 11, apresentei sintomas de covid-19 pela primeira vez. Com febre muito alta dor no corpo e dificuldade para respirar fiquei incapacitado de iniciar a Atividade2 como havia planejado. Precisei parar inclusive minhas atividades na empresa onde trabalho por conta dos fortes sintomas.
Gostaria de perguntar o que podemos fazer para que eu não perca esse início de semestre, haja vista que essa semana ainda não terei condições de retomar minhas atividades.

No aguardo...

Desde já grato pela atenção.

**Comment by kyriosdata** [comment]
Olá Paulo,

observe a orientação do seu médico (isto tem prioridade). Cuide da sua saúde, minha orientação.

Satisfeita a necessidade de saúde que você tem agora, se não houver impedimento, você pode continuar realizando as atividades e daremos uma atenção específica ao seu caso (quanto aos prazos das atividades). Tanto eu quanto o Prof. Plínio (@plinioleitao), ok?

Adicionalmente, tal questão pode ser tratada via email ou outra forma. Também sugiro informar a coordenadora do curso, pois possivelmente esta não é a única disciplina afetada. 

Melhoras.

**Comment by MMHIT** [comment]
Prezados Professores, Boa Noite!
Agradeeço imensamente pela atenção e cuidado com minha situação.
Volto para comunicar boas notícias, o que me afligiu não era covid, todos os testes deram negativo, foram sintomas de uma amigdalite aguda que são bem parecidos com os sintomas da covid, neste momento já me encontro recuperado e pronto para retomar minhas atividades.

como podemos proceder para com os prazos?

desde já grato pela atenção.

**Comment by kyriosdata** [comment]
Fico contente com sua recuperação. Saúde!

Quanto às atividades, simplesmente as execute. No momento oportuno daremos (eu e @plinioleitao) a devida atenção.
