### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by im-pokz** [kyriosdata/oo#159]
i)
- Objeto "iPad", da classe "Tablet";
- Objeto "Caneta Branca", da classe "Canetas";
- Objeto "Óculos Preto", da classe "Óculos.

ii)
- Objeto "Janela Quadrada", da classe "Janelas";
- Objeto "Telha Marrom", da classe "Telhas";
- Objeto "Porta Branca", da classe "Portas"

iii)
- Objeto "Goleiro", da classe "Jogadores";
- Objeto "Árbitro Assistente", da classe "Árbitros";
- Objeto "Arquibancada inferior", da classe "Arquibancadas".

**Comment by kyriosdata** [comment]
Observação IMPORTANTE. Classificação é diferente de coleção. Ou seja, o plural não é um recurso natural quando se denomina uma classe. Por exemplo, "portas" sugere uma coleção de portas e não a classificação de um objeto. Ou seja, nome de classe no singular.

COM APROVEITAMENTO. 👍
