### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by alisson-b** [kyriosdata/oo#161]
i. Objeto "Iphone" da classe "Smartphone"
   Objeto "Ipad" da classe "Tablet"
   Objeto "Canetão azul" da classe "Canetão"

ii. Objeto "Janela branca" da classe "Janela"
    Objeto "Maçaneta verde" da classe "Maçaneta"
    Objeto "Vidro para janela" da classe "Vidro"

iii. Objeto "Goleiro" da classe "Jogador"
     Objeto "Repórter" da classe "Imprensa"
     Objeto "Bandeira de escanteio" da classe "Bandeira"

**Comment by kyriosdata** [comment]
Observações:

- Repórter não seria da classe Repórter? Imprensa é formada, é composta de, dentre outros elementos, de repórteres.
- Bandeira de escanteio, como o próprio nome, é uma bandeira. Contudo, talvez também pudesse ser classificada como uma Marca, assim como a marca do pênalti. 

Muito bom. COM APROVEITAMENTO. 👍
