### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by calebesz** [kyriosdata/oo#162]
Figura 1 - "Camiseta SVBPERBIA verde" da classe camiseta. // "Fone de ouvido Branco" da classe "Fone de ouvido" // "Iphone branco" da classe "Celular"

Figura 2 - "Telhado vermelho" da classe Telhado //  "Parede verde" da classe "Parede" // "Porta branca" da classe "Porta"

Figura 3 - "Goleiro" da classe "Jogadores" // "Área" da classe "Campo" // "Torcedor" da classe "Torcida"

**Comment by plinioleitao** [comment]
Prefira o singular, 'Jogador' em vez de 'Jogadores'. Ainda, vale refletir sobre Torcedor: Torcedor é um objeto da classe Torcida, ou Torcida possui Torcedores? (@kyriosdata pode comentar). 
COM APROVEITAMENTO.
