### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by MatheusPe** [kyriosdata/oo#163]
Bom dia professor! Infelizmente me perdi um pouco com as datas em meio esse tempo de adaptações de atividades e aulas a distância, sempre fazendo uma coisa e outra mas sem aquele contato com o professor que facilita na hora de organizar as atividades. Pensei que a entrega da atividade 02 fosse para o dia da aula dessa semana, mas percebi que estava errado. Não sei se o senhor vai aceitar, mas vou mandá-la por a aqui por conta dos motivos já explicados. Lhe desejo um bom dia!

Reflexão - 

Acredito que mesmo sendo possível a conversão de um código C++ Orientado a objetos para um código C, isso não muda o fato de que as linguagens trabalham de forma diferente. Construir um código em C++ é diferente de construir um Código em C, pois C++ pode ser usada orientada a objetos enquanto C é uma linguagem mais procedural. É possível ganhar toda uma flexibilidade fornecida pelas linguagens OO, onde se é possível focar mais nos objetos do que na ação e lógica em si de uma linguagem procedural. E por fim, adaptar um código a uma ferramenta que não necessariamente desenvolvida para aquilo pode deixar o código menos eficiente e menos legível.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código.
COM APROVEITAMENTO.
