### ISSUE TITLE
"Classificação" 

### ISSUE THREAD

**Issue by taynasantana** [kyriosdata/oo#167]
Primeira figura : 
"Camisa Svperbia" da classe "Camisa"
"Caneta Sharpie" da classe "Caneta"
"Lápis preto" da classe "Lápis".
Segunda figura:
"Janelas grandes" da classe "Janelas".
"Portas brancas" da classe "Portas".
"Telhado" da classe " Telhado".
Terceira figura:
"Arbitro" da classe "Arbitro".
"Goleiro" da classe " Jogador".
"Torcedor" da classe " Torcida".

**Comment by kyriosdata** [comment]
Observações:

- Classes são nomeadas no singular, pois não representam uma coleção. Assim a classe Janelas sugere algo diferente da simples classe Janela.  O mesmo vale para Portas. O melhor é Porta. 

- Torcedor é da classe Torcedor. Torcida, por outro lado, reúne torcedores. Noutras palavras, um torcedor não se confunde com Torcida. 

Muito bom. COM APROVEITAMENTO. 👍
