### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by grootersluiz** [kyriosdata/oo#169]
i. O título refere-se a uma análise detalhada dos processos que serão realizados utilizando o software que será desenvolvido, o que permitirá uma amplitude de visão no momento de desenvolver o mesmo, resultando em um produto dinâmico e flexível, cujos módulos poderão tanto operar em conjunto, quanto operar individualmente, de forma eficaz.

ii. UML

iii. Sim, ambos são pesquisas sobre a importância da visão sistêmica no momento de desenvolver um software, o que nos leva a priorizar o paradigma de OO, pois nos possibilita criar um produto mais eficiente.

**Comment by plinioleitao** [comment]
1) O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
2) OK
3) OO é um instrumento para decomposição do problema e da solução. Na perspectiva da solução, os recursos de OO (ex. classe, herança, etc.) são empregados para estruturar o software. (@kyriosdata pode complementar).
COM APROVEITAMENTO.
