### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by grootersluiz** [kyriosdata/oo#170]
i. camiseta Svperbia, classe: Camiseta.
   smartphone Apple, classe: Smartphone.
   oculos Preto, classe: Oculos.
ii. janela Branca, classe: Janela.
   parede Verde, classe: Parede.
   casa Classica, classe: Casa.
iii. torcedor Casa, classe: Torcedores.
     jodador Titular, classe: Jogador.
     harbitro Auxiliar, classe: Harbitro.

**Comment by plinioleitao** [comment]
Prefira o singular, 'Torcedor' em vez de 'Torcedores'. 
COM APROVEITAMENTO.
