### ISSUE TITLE
Fundamentos

### ISSUE THREAD

**Issue by SleepyDarlin** [kyriosdata/oo#174]
Coloquei explicação por quê me ajudou a mentalizar as dificuldades que tive.
Slides dificeis:
11 - por não saber java, tive que ir atrás de algo que pudesse me explicar o que significava cada passo desse slide, o que me trouxe um pouco de dificuldade pra entender, mas nada que não pudesse ser superado. 
36 e 37 - muita informação, fiquei perdido e tive que reler os slides umas 4x até conseguir entender

Slides fáceis
30- bem intuitivo, as imagens deixam bem claro a teoria e encaixam bem com a descrição
6 e 7 - deixam bem claro que orientação a objeto é uma forma diferente de enxergar as coisas

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
