### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by valeriateles** [kyriosdata/oo#175]
figura 1:
lápis de grafite amarelo: classe lápis;
caneca de café: classe caneca;
óculos de grau preto: classe óculos;
figura 2:
telhado marrom duas águas: classe telhado;
janela gradeada, retangular com vidro: classe janela;
vidro fume retangular para janela: classe vidros;
figura 3:
torcedor do time da casa: classe torcedor;
jogador do time da casa: classe jogador;
propaganda mastercard: classe publicidade;

**Comment by kyriosdata** [comment]
Observação. Em vez da classe denominada "Vidros", melhor seria "Vidro". Vidros sugere coleção e não classificação. 

Muito bom. COM APROVEITAMENTO. 👍
