### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by felipekafuri** [kyriosdata/oo#178]
i. O título no meu ver, o titulo tenta previnir o que chamamos de "Over engineering", que consiste em trabalhar em cima de um código seja refatorando-o ou modularizando-o prematuramente, o que geral um atraso na entrega do produto e possivelmente uma ma modularização do código.

ii. UML

iii. Sim, ambos os artigos falam sobre organição na hora de se desenvolver o software.

**Comment by plinioleitao** [comment]
i. O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista. Dessa forma, pode-se decompor: o problema, uma solução existente e uma solução em construção. Neste último, há a decomposição de uma ideia que existe apenas na nossa cabeça.
ii. OK
iii. OO é um instrumento para decomposição do problema e da solução. Na perspectiva da solução, os recursos de OO (ex. classe, herança, etc.) são empregados para estruturar o software. 
COM APROVEITAMENTO.
