### ISSUE TITLE
Meu repositório

### ISSUE THREAD

**Issue by wevertoum** [kyriosdata/oo#179]
Meu nome: Weverton Ferreira Rodrigues
Meu registro acadêmico: 201705650
Minha conta no Github: https://github.com/wevertoum/poo-2020-01

**Comment by wevertoum** [comment]
Peço desculpas, eu passei por uma fase muito complicada com mudanças e falta de internet la em casa, acabou que me atrasei no conteúdo e estou tentando correr atrás, att

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
