### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by wevertoum** [kyriosdata/oo#181]

**Comment by wevertoum** [comment]
Seguindo o tópico citado [aqui](https://github.com/kyriosdata/oo/blob/master/topicos/02.md), podemos refletir que pelo fato de C ser um linguagem de nível mais baixo (com uma melhor manipulação no alocamento de memória, como no caso do uso de ponteiros) com uma velocidade considerável de processamento, a priori, parece ser uma boa opção construir aplicações usando essa tecnologia, mas com um paradigma mais humanizado, mais versátil, podemos ter um melhor aproveitamento no desenvolvimento de uma aplicação. No momento de coletar os requisitos com stakeholders já conseguimos imaginar uma solução quando se usa um paradigma orientado a objetos, dada sua proximidade com o mundo real

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código.
Vale ressaltar que as fases de requisitos e de design são independentes e, ao menos conceitualmente, na definição formal, não se deve tomar decisões de projeto (design) na fase de requisitos.
COM APROVEITAMENTO.
