### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by felipekafuri** [kyriosdata/oo#182]
i. lapis Madeira classe Lapis
foneDeOuvido Apple classe Fone
notebook Apple classe Notebook

ii. porta Branca classe Porta
janela Redonda classe Janela
janela Quadrada classe Janela

iii. campoDeGrama Gramado classe Campo
torcedor Casa classe Torcedor
goleiro Casa classe Jogador

**Comment by kyriosdata** [comment]
Muito bom. COM APROVEITAMENTO. 👍
