### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by guilhermefaleiros** [kyriosdata/oo#186]
Figura 1:
- Iphone Branco - Classe: Smartphone
- Óculos de Grau Preto - Classe: Óculos
- Caneca Vermelha - Classe: Caneca

Figura 2:
- Porta Branca - Classe: Porta
- Janela de Vidro - Classe: Janela
- Casa com Muro Verde - Classe: Casa

Figura 3:
- Jogador de Futebol - Classe: Atleta
- Campo de Futebol - Classe: Campo
- Torcedor do Time da Casa - Classe: Torcedor

**Comment by plinioleitao** [comment]
Reflita sobre 'Torcedor do Time da Casa', pois se refere a um objeto cuja 'duração' é uma única partida. (@kyriosdata pode comantar)
COM APROVEITAMENTO.
