### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by giancarlobara** [kyriosdata/oo#188]
i. canetao Azul da classe Canetao; canetao Vermelho da classe Canetao;iphone da classe Smartphone.
ii.porta Branca da classe Porta; chamine De Tijolo da classe Chamine; janela Com Vidro da classe Janela.
iii.seguranca da classe Funcionario; goleiro da classe Jogador; torcedor da classe Pessoa.

**Comment by kyriosdata** [comment]
Muito bom. COM APROVEITAMENTO. 👍
