### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by calebesz** [kyriosdata/oo#189]
classe: sim
objeto: sim
associação reflexiva: não
agregação: sim
composição: sim
cardinalidade de associação: não
atributo de classe: sim
nome de classe: sim
métodos de classe: sim
pacote (package): sim
dependência: sim
interface (usando círculo): não
interface (usando retângulo com indicação de estereótipo): sim
implementação de interface por uma classe: não
nota: sim
associação entre nota e elemento anotado: não
uso de interface: sim
herança: sim
classe abstrata: sim

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Elementos para os quais a resposta foi "não" serão trabalhados posteriormente.
