### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by Thyago-C** [kyriosdata/oo#193]
i)
*Objeto: Fone de ouvido - Classe: Dispositivo de áudio
*Objeto: Camiseta SVPERBIA - Classe: Camiseta
*Objeto: LapTop - Classe: Computador

ii)
*Objeto: Porta branca - Classe: Porta
*Objeto: Maçaneta verde - Classe: Maçaneta
*Objeto: Janela branca - Classe: Janela

iii)
*Objeto: Goleiro - Classe: Jogador
*Objeto: Apito - Classe: Ferramenta de arbitragem
*Objeto: Filmadora preta - Classe: Filmadora

**Comment by kyriosdata** [comment]
Muito bom. COM APROVEITAMENTO. 👍
