### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by andrey-dias** [kyriosdata/oo#194]
Figura 1: Classe camiseta -> camiseta verde da marca Svperbia; Classe Apple -> Ipad, Iphone e Macbook; Classe Câmera -> Câmera  Canon;
Figura 2: Classe telhado -> telha de barro; Classe janela -> Janela branca quadrada; Classe porta -> Porta branca;
Figura 3: Classe torcida -> torcedor; Classe lugaresDoEstadio -> arquibancada; Classe jogadores -> Volante;

**Comment by kyriosdata** [comment]
Observação. 

- Telhado é formado por uma agregação de telhas. Ou seja, uma associação entre Telhado e Telha. Noutras palavras, não classificaria telha como telhado. 

- O nome de uma classe é no singular, pois classifica um elemento. Uma classe não é uma coleção como uma lista, por exemplo. Ou seja, LugarDoEstadio em vez de LugaresDoEstadio. O mesmo para Jogador. 

COM APROVEITAMENTO. 👍

**Comment by andrey-dias** [comment]
Certo professor obrigado pelas correções
