### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by pavaladao** [kyriosdata/oo#195]
i. 1 - Objeto: Câmera fotográfica 
       Classe: Equipamentos eletrônicos
  2 - Objeto: Caneta
       Classe: Materiais escolares
 3 - Objeto: Camisa
       Classe: Roupa

ii. 1 - Objeto: Telha de barro
       Classe: Telha
  2 - Objeto: Janela circular
       Classe: janela
  3 - Objeto: Porta branca
       Classe: Porta

iii. 1 - Objeto: Goleiro
       Classe: Jogador
  2 - Objeto: Campo de futebol
       Classe: Campo
  3 - Objeto: Grama para campo de futebol
       Classe: Gramínea

**Comment by plinioleitao** [comment]
Prefira o singular: 'Equipamento eletrônico' em vez de 'Equipamentos eletrônicos'. 
COM APROVEITAMENTO.
