### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by pavaladao** [kyriosdata/oo#198]
i. O título do artigo sugere que, apesar de ainda não existir, nós podemos pensar em um novo sistema decomposto, ou seja, pensar nas partes menores do sistema primeiro e ir construindo o mesmo ,à medida que interligamos essas partes menores.

ii. O instrumento empregado para documentar a estrutura de um software nesta disciplina é a UML (Unified Modelling Language).

iii. A relação entre os artigos e a Orientação a Objetos é muito explícita , já que esse paradigma é baseado em modularizar e encapsular o projeto em pequenas partes, com base nas suas características comuns, antes mesmo de se codificar. E para tal tarefa a UML facilita que a maneira com que esse projeto foi repartido, seja compreendido por outras pessoas que não estiveram relacionadas com a criação desse projeto.

**Comment by plinioleitao** [comment]
O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
