### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by Lapot300** [kyriosdata/oo#199]
Primeira Figura:

- Ipad - Classe: Tablet
- Iphone - Classe : Smartphone
- Camisa Verde - Classe : Roupa

Segunda Figura:

- Janela de Vidro - Classe: Janela
- Porta Branca - Classe: Porta
- Casa Verde - Classe: Casa

Terceira Figura:

- Jogador de Futebol - Classe : Atleta
- Torcedor - Classe: Pessoa
- Campo de Futebol - Classe: Campo

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
