### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by HenriqueMartinsCosta** [kyriosdata/oo#200]
# i
### 1
**Objeto:** _Celular_
**Classe:** _Dispositivos Eletrônicos_
### 2
**Objeto:** _Óculos_
**Classe:** _Vestíveis_
### 3
**Objeto:** _Tesoura_
**Classe:** _Materiais de Escritório_
# ii
### 1
**Objeto:** _Porta da frente_
**Classe:** _Portas_
### 2
**Objeto:** _Janela da direita_
**Classe:** _Janelas_
### 3
**Objeto:** _Tinta Verde_
**Classe:** _Revestimentos_
# iii
### 1
**Objeto:** _Goleiro_
**Classe:** _Jogador_
### 2
**Objeto:** _Cameraman_
**Classe:** _Jornalistas_
### 3
**Objeto:** _Mastercard_
**Classe:** _Patrocinadores_

**Comment by plinioleitao** [comment]
O singular quase sempre é empregado. Então, prefira ‘Dispositivo eletrônico’ em vez de ‘Dispositivos eletrônicos’. 
COM APROVEITAMENTO.
