### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by Lapot300** [kyriosdata/oo#202]
1. O título "decompor sistemas em módulos'"sugere que a solução do problema  pode ser alcançada "decompondo" o problema, ou seja, dividindo o problema em problemas menores e resolver 1 por 1. 

1. Na nossa disciplina, qual o instrumento empregado para documentar a estrutura de um software (conforme a ementa) é o UML.

1. Programação Orientada a Objeto é usado para decompor o problema e a solução, resolvendo o problema total mais rapidamente e facilmente, utilizando os recursos de OO (classe, objeto, herança, etc)  para estruturar o software.

**Comment by plinioleitao** [comment]
O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
