### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by HenriqueMartinsCosta** [kyriosdata/oo#203]
**i.** Sim
**ii.** Sim
**iii.** Não
**iv.** Não
**v.** Não
**vi.** Não
**vii.** Sim
**vii.** Sim
**ix.** Não
**x.** Não
**xi.** Sim
**xii.** Não
**xiii.** Não
**xiv.** Não
**xv.** Não
**xvi.** Não
**xvii.** Não
**xviii.** Sim
**xix.** Não

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Elementos para os quais a resposta foi "não" serão trabalhados posteriormente. 
De qualquer forma, notei "muitos" nãos. A intenção não era compreender ou conhecer, conforme o exercício pedia. A intenção era apenas reconhecer o elemento gráfico na UML, de alguma forma abordado no item em questão. De qualquer forma, vamos trabalhar isso.
