### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by Moreira-code** [kyriosdata/oo#204]
i.  Classe Escola
          caderno,
          lápis
          caneta

    Classe Eletrônico

          Camera_Fotografica
          Celular
          Tablet
          
     Classe Acessorios

          Fone
          Oculos
          Camisa

ii.  

     Classe Casa

           Porta 
           Janela 
           Telhado

      Classe Telhado

            Telha
            Chaminé
            Gesso

      Classe Porta

            Fechadura
            Chave
            Pintura
  
iii.  

       Classe Torcedor

              Pessoa
              Time
              Cadeira

       Classe Campo

              Gramado
              Gol
              Bola
              
       Classe Jogador

             Time
             Chuteira
             Camisa

**Comment by plinioleitao** [comment]
Em alguns casos, as suas escolha referem-se à ocorrência de agregação, em vez de 'classificação': Telhado possui telha e chaminé; Porta possui fechadura; Jogador possui chuteira; Campo possui gramado; etc. (@kyriosdata)
COM APROVEITAMENTO.

**Comment by kyriosdata** [comment]
Embora um jogador possui chuteira esteja correto, por exemplo, também são possíveis outras interpretações, como "jogador usa chuteira".
