### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by Lapot300** [kyriosdata/oo#205]
1. Classe  - Sim

1. Objeto - Sim

1. Associação reflexiva - não

1. Agregação -  Sim

1. Composição - Não

1. Cardinalidade de associação  - não

1. Atributo de classe - Sim

1. Nome de classe - Sim

1. Métodos de classe - Sim

1. Pacote (package) - Sim

1. Dependência - Sim

1. Interface (usando círculo) - Não

1. Interface (usando retângulo com indicação de estereótipo) - Não

1. Implementação de interface por uma classe - Não

1. Nota - Sim

1. Associação entre nota e elemento anotado - Não

1. Uso de interface - Não

1. Herança - Sim

1. Classe abstrata - Sim

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Elementos para os quais a resposta foi "não" serão trabalhados posteriormente.
