### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by HenriqueMartinsCosta** [kyriosdata/oo#206]
**i.** Sim, acho que eu seria capaz de implementar uma classe simples em Java, mas provavelmente eu precisaria de consultar materiais na internet pois nunca programei nessa linguagem.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Ótimo! Então terá oportunidades para desenvolver suas habilidades, tanto de programação quanto na linguagem Java, especificamente.
