### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by Lapot300** [kyriosdata/oo#207]
Eu nunca programei em nenhuma linguagem orientada a objeto,  mas sendo bem sincero, como eu entendo o básico do UML ( classe, atributos,etc) então com alguns minutos consultando o StackOverflow ( ou na própria documentação da linguagem)  eu acho que consigo  implementar uma  classe em java.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Artur, o primeiro passo já está dado, você possui sua própria avaliação e até possíveis caminhos. Estamos aqui para ajudar.
