### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by pablofurtado** [kyriosdata/oo#208]
i. Smartphone  -  Classe: Aparelhos eletrônicos
  Xícara de café  -  Classe: Bebida
  Camiseta verda  -  Classe: Roupa

ii. Vidro  -  Classe: Janela
   Chaminé  -  Classe: Telhado
   Maçaneta  -  CLasse: Porta

iii. Goleiro  -  Classe: Jogador
    Juiz  -  Classe: Arbitragem
    Linhas laterais  -  Classe: Campo

**Comment by plinioleitao** [comment]
O singular quase sempre é empregado. Então, prefira ‘Aparelho eletrônico’ em vez de ‘Aparelhos eletrônicos’. 
Avalie associações que podem denotar agregação em vez de 'classificação'; por exemplo, Telhado possui Chaminé, Porta possui Maçaneta. Reflita também sobre o objeto Café (em vez de Xícara de Café) da classe Bebida. Ainda, 'Linhas Laterais' é um objeto da classe 'Campo'? (@kyriosdata)
COM APROVEITAMENTO.
