### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by atilaufg** [kyriosdata/oo#209]
Três objetos e três classes.
Figura 1:
 -Pincel Bic Preto da classe Pincel.
 -Pincel Bic Vermelho da classe Pincel.
 -Pincel Pilot Azul da classe Pincel.
Figura 2:
 -Azulejo Branco da classe Pisos.
 -Cimento Queimado da classe Pisos.
 -Mármore Liso da classe Pisos.
Figura 3:
 -Atacante da classe Jogador.
 -Goleiro da classe Jogador.
 -Zagueiro da classe Jogador.

**Comment by plinioleitao** [comment]
O singular quase sempre é empregado. Então, prefira ‘Piso’ em vez de ‘Pisos’. 
Tente explorar outras classes da figura.
COM APROVEITAMENTO.
