### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by SleepyDarlin** [kyriosdata/oo#210]
i.  1. "Câmera Nikon " da classe  "Câmera fotográfica"
    2. "iPhone" da classe "Smartphone"
    3. "Camisa SVPERBIA" da classe "Camisa"

ii. 1. "Fluxo de ar" da classe "Conforto interno"
    2.  "Telhado" da classe "Construção"
    3. "Sofá" da classe "Móveis"

iii. 1. "Cinegrafista da Band" da classe "Cinegrafista"
     2. "Segurança do portão esquerdo" da classe "Segurança"
     3. "Narrador do ESPN" da classe "Narrador"

**Comment by plinioleitao** [comment]
Em "Telhado" da classe "Construção", esta é uma associação que requer contexto específico para sua existência, tal como "Construção de Telhado".
Veja que "Segurança do Portão Esquerdo" está ligado a uma partida específica, então requer melhor reflexão (@kyriosdata).
COM APROVEITAMENTO.
