### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by samirmont0** [kyriosdata/oo#211]
**i.**
- Camiseta SUPERBIA (Classe Roupa)
- Iphone (Classe Celular)
- Óculos (Classe Acessório)

**ii.**
- Porta branca (Classe Porta) 
- Janela com vidro (Classe Janela)
- Chaminé de tijolo (Classe chaminé)

**iii.**
- Repórter Esportivo (Classe Repórter) 
- Bandeira de escanteio (Classe Bandeira)
- Jogador de futebol (Classe Atleta)

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
