### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by Zanphs** [kyriosdata/oo#214]
i. A decomposição de sistemas em módulos dita pelo título, ao meu entendimento sugere uma partição de um problema grande (geralmente complexo) em menores problemas possivelmente mais simples, para que sejam resolvidos primariamente e, posteriormente, a união da resolução dos problemas menores solucione o problema inicial maior.
ii. O UML é o instrumento empregado para documentar a estrutura de um software na disciplina.
iii. A modularização e decomposição em módulos citadas no artigo se relacionam perfeitamente com OO, dito que a estrutura da orientação a objetos se define em módulos maiores e menores, com ou sem ancestralidade e muitas vezes decompostos exatamente com o mesmo intuito da decomposição citada no artigo.

**Comment by plinioleitao** [comment]
O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
