### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by MatheusPe** [kyriosdata/oo#216]
i, O título sugere decompor um sistema em módulos para que ele tenha mais flexibilidade e compreensividade ao mesmo tempo que diminui o tempo de desenvolvimento do sistema. Não necessariamente precisa-se do todo para decompor em partes, também há a possibilidade de construir partes e formar o todo.

ii. Na nossa disciplina é o UML.

iii. Consigo, já que a linguagem OO trabalha justamente com isso, formar as partes (Objetos), e ligar com o todo através de algumas técnicas como herança e polimorfismo, construindo o todo. Trabalha-se com o desenvolvimento de módulos que constituem um código.

**Comment by plinioleitao** [comment]
O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
