### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by schloegl10** [kyriosdata/oo#217]
Já realizei uma boa quantia de projetos Orientados a objetos em java, assim como trabalhei em estágio onde era usado o paradigma de programação Orientado a Objetos na linguagem Groovy (toda a base de sintaxe e logica do java). Então acredito ser capaz de realizar a criação de classes, objetos e métodos.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Ótimo!
