### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by schloegl10** [kyriosdata/oo#218]
1. classe- sim 
2. objeto - sim
3. associação reflexiva - sim
4. agregação - sim
5. composição - sim
6. cardinalidade de associação - sim
7. atributo de classe - sim
8. nome de classe - sim
9. métodos de classe - sim
10. pacote (package) - sim
11. dependência - sim
12. interface (usando círculo) - sim
13. interface (usando retângulo com indicação de estereótipo) - sim
14. implementação de interface por uma classe - sim
15. nota - não
16. associação entre nota e elemento anotado - não
17. uso de interface - sim
18. herança - sim
19. classe abstrata - sim

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Elementos para os quais a resposta foi "não" serão trabalhados posteriormente.
