### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by MateSilver** [kyriosdata/oo#219]
1. No primeiro artigo, vemos que modularização de um algoritmo, desde seu planejamento, vem no desenvolvimento inicial para dividir tarefas e trabalhos. De forma a deixar tudo mais organizado para ser trabalhado por varias pessoas e modificado de maneira rápida.
2. creio que o UML seja usada na nossa matéria para documentar uma estrutura.
3. todos os artigos trazem enfase em como a estrutura do software deve ser dividida e organizada para facilitar e dividir tarefas e processos, deixando códigos bem definidos e divididos, seja em módulos ou estruturas organizadas.

**Comment by plinioleitao** [comment]
O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
