### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by AlvesMarina** [kyriosdata/oo#220]
i. sim
ii. sim
iii. não
iv. sim
v. sim
vi. não
vii. sim
viii. sim
ix. sim
x. sim
xi. não
xii. não
xiii. sim
xiv. não
xv. sim
xvi. sim
xvii. não
xviii. não
xix. sim

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Elementos para os quais a resposta foi "não" serão trabalhados posteriormente.
