### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by FerreiraRaphael** [kyriosdata/oo#222]
1. Mesmo que o sistema ainda não exista, sua solução, pode ser pensada de forma modular.

2. UML

3. Os dois artigos apresentam formar de resolver problemas dividindo eles em diferentes partes, com diferentes responsabilidades. A programação orientada a objeto é uma solução que tem diferentes objetos, com diferentes responsabilidades.

**Comment by plinioleitao** [comment]
O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
