### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by sarahgalves** [kyriosdata/oo#225]
i. O título do artigo sugere, mesmo ainda não existindo, é possível decompor o sistema em partes menores (em módulos) e a medida que construindo essas partes menores, vamos ligando a outras partes (também menores que o sistema num todo).

ii. Na nossa disciplina, UML é o instrumento empregado para documentar a estrutura de um software, conforme a ementa.

iii. A ligação entre os artigos e a orientação a objetos é dada pelo assunto de decompor em partes menores para resolver o problema/desenvolver o sistema de forma mais fácil e rápida. Em OO, por exemplo, temos como recurso as classes, herança, objetos, entre outros.

**Comment by plinioleitao** [comment]
O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
