### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by sarahgalves** [kyriosdata/oo#227]
i. "camisa SVPERBIA" da classe "Camisa"; "caderno espiral" da classe "Caderno"; "celular Iphone" da classe "Celular".

ii. "janela redonda" da classe "Janela"; "janela retangular" da classe "Janela"; "porta de madeira" da classe "Porta".

iii. "bandeirinha" da classe "Árbitro"; "goleiro" da classe "Atleta"; "jogador do time da casa" da classe "Atleta".

**Comment by plinioleitao** [comment]
Veja que "jogador de time da casa" para a classe "Atleta" é uma associação dependente do partida em si, e por isso requer melhor reflexão (@kyriosdata pode acrescentar mais comentários aqui).
COM APROVEITAMENTO.
