### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by driellyg** [kyriosdata/oo#228]
i. Fone de ouvido - Classe "Acessórios eletrônicos"
Caneca - Classe "Utensílios domésticos"
Iphone - Classe "Smartphones"
ii. Vigota de madeira - Classe "Materiais de construção"
Telha marrom - Classe "Material para telhado"
Maçaneta verde - Classe "Porta"
iii. Goleiro - Classe "Jogador"
Campo de Futebol - Classe "Esporte"
Arquibancada - Classe "Estádio"

**Comment by plinioleitao** [comment]
O singular quase sempre é empregado. Então, prefira, por exemplo, ‘Smartphone’ em vez de ‘Smartphones’. 
A associação entre Maçaneta e Porta é melhor entendida como agregação, visto que ‘porta tem maçaneta’, o mesmo se aplica para a associação entre Arquibancada e Estádio. Vale também rever a associação entre Campo de Futebol e Esporte. (@kyriosdata pode agregar outros comentários aqui).
COM APROVEITAMENTO.
