### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by driellyg** [kyriosdata/oo#230]
i. No caso do desenvolvimento de um novo sistema, a decomposição que ocorre inicialmente é do problema a ser resolvido por aquele software. Se eu tenho um problema ao fritar um ovo e preciso desenvolver um software para me auxiliar, basta decompor ele em etapas menores, para que o processo se torne mais fácil;

ii. O instrumento utilizado para documentar a estrutura de um software, em nossa disciplina, será a UML. Ela se trata de uma linguagem-padrão para a elaboração da estrutura de projetos de software. Essa linguagem pode ser utilizada para a visualização, a especificação, a construção e a documentação de artefatos que façam uso de sistemas complexos de software

iii. A linguagem UML é utilizada para definir uma série de artefatos auxiliando na modelagem e documentação de sistemas orientados a objetos. Essa modelagem e documentação acontece através de classes e seus atributos na UML. Para que possamos chegar nessas classes de um objeto, necessitamos da decomposição daquele todo;

**Comment by plinioleitao** [comment]
O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
