### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by atilaufg** [kyriosdata/oo#231]
1 - Entendo pelo título sobre critérios que são usados para divisão e agrupamento de sistemas. O artigo sugere formas de decompor sistemas em módulos a fim de facilitar todo o processo (desenvolvimento, estudo, flexibilidade, etc).
2 - Logo na primeira página da ementa esta empregado o uso do UML, que é usado pra elaborar e estruturar todo processo de software (documentar todo processo).
3 - Com a necessidade de segmentar e modular um sistema, a fim de facilitar todo o processo, inclusive a organização em módulos do sistema antes de cria-lo; e sempre documentar o sistema para evitar um colapso de informações necessárias para manter e atualizar o software. Conseguimos obter estas necessidades em OO que emprega o uso de classes e objetos (modulação) junto á documentação geral.

**Comment by plinioleitao** [comment]
O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
