### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by im-pokz** [kyriosdata/oo#234]
i) Ao começar o desenvolvimento de um software, é necessário ter em mente qual o problema ele vai resolver e como. Com isso, deve-se dividir o problema principal em pequenos módulos e ,assim, ir resolvendo-os gradativamente, para facilitar e simplificar o processo. É como se fosse uma receita, onde você deve seguir etapas até chegar à "resolução" definitiva da questão em si. 

ii)  O instrumento utilizado para modularizar e documentar a estrutura de software é a UML. Essa linguagem é utilizada para a elaboração da estrutura de projetos de software que possui grande utilidade na visualização, especificação, construção e documentação de características, módulos e estruturas que são utilizadas em um software.

iii) A UML é totalmente ligada à OO. Pelo fato de ser um padrão de modelagens de dados/ informações a fim de obter uma visão holística de todo projeto ou processos, ela se relaciona diretamente com a necessidade de obter e empregar o uso de classes e objetos, que são, de certa forma, módulos.

**Comment by plinioleitao** [comment]
O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
