### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by alisson-b** [kyriosdata/oo#235]
i. A interpretação do título por mim estabelecida, é de que "decompor sistemas em módulos" não significa exclusivamente a decomposição de um sistema pronto, mas também a fragmentação do projeto de um sistema anteriormente ao processo de software, ou seja, durante o planejamento.

ii. O instrumento empregado para documentar a estrutura de um software em nossa disciplina será a UML.

iii. Sim, pois em Orientação a Objetos os programas são desenvolvidos utilizando de classes, e outras ferramentas, que podem ser correlacionado como uma espécie de decomposição do algorítimo(problema) em partes.

**Comment by plinioleitao** [comment]
O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
