### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by alisson-b** [kyriosdata/oo#237]
i. classe - sim
ii. objeto - sim
iii. associação reflexiva - não
iv. agregação - sim
v. composição - sim
vi. cardinalidade de associação - não
vii. atributo de classe - sim
viii. nome de classe - sim
ix. métodos de classe - sim
x. pacote (package) - sim
xi. dependência - sim
xii. interface (usando círculo) - não
xiii. interface (usando retângulo com indicação de estereótipo) - não
xiv. implementação de interface por uma classe - não
xv. nota - sim
xvi. associação entre nota e elemento anotado - sim
xvii. uso de interface - sim
xviii. herança - sim
xix. classe abstrata - não

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Elementos para os quais a resposta foi "não" serão trabalhados posteriormente.
