### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by giancarlobara** [kyriosdata/oo#238]
i.Parmas introduz a ideia de pensar um escopo de projeto previamente dividido. Este desmembramento trás a ideia de filtrar antecipadamente as funcionalidade a serem desenvolvidas, para que, elas possam ser geradas independentemente do todo final maior, onde o ganho de tempo, performance, gerenciamento, deste sistema antes modelado e arranjado, traria maior benefício posteriormente ao trabalho. O título sugere uma análise prévia do comportamento do sistema antes da implementação e com isso, após a compreensão de todas as partes nele necessárias, a divisão em módulos a serem trabalhados separadamente, que no fim gere um todo fragmentado e fácil de gerenciar caso houvessem problemas.
ii.Esse instrumento é a UML.
iii.Sim. A orientação a objetos nos permite  trabalhar com métodos aplicados a objetos separadamente, essa condição nos proporcionam fragmentar parte do sistema final em estruturas menores e as trabalharem em parte, como a ideia defendida por Parnas nos dois artigos .

**Comment by plinioleitao** [comment]
O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
