### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by guilhermefaleiros** [kyriosdata/oo#241]
i. Em minha visão, o título se refere a modularização do sistema baseado em regras de negócio, ou seja, é necessário interpretar o problema e decompar em módulos que fazem sentido estarem juntos de modo a melhor a organização e tornando o processo de construção do sistema um pouco menos complexo.
ii. Se fará uso dos diagramas de UML.
iii. Sim, a Orientação a Objetos é muito utilizada para a modularização de um determinado sistemas, por justamente, dividir o sistema com abstrações a fim de atender a regra de negócio com uma linguagem mais clara e fácil de refletir a real solução do problema.

**Comment by plinioleitao** [comment]
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
