### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by andrey-dias** [kyriosdata/oo#242]
1 - Em minha interpretação o título remete ao fato da busca por critérios técnicos e práticos no momento de criação de cada módulo de um sistema em desenvolvimento, tendo em vista que o próprio conceito de modularização em software remete à organização, os critérios são essenciais na busca por uma padronização tornando o projeto mais limpo e menos complexo.

2 - A documentação é estruturada através da UML.

3 - Sim, visto que a orientação à objetos é uma forma de tratar o software como classes que contém métodos e atributos, em outras palavras módulos, que priorizam a organização, manutenção, melhor divisão de trabalho no projeto e simplificar a interpretação e absorção de problemas em um projeto.

**Comment by plinioleitao** [comment]
O título 'decompor sistemas em módulos' sugere que a solução do problema (ou seja, o software) pode ser 'desmembrado em partes menores', mesmo que o software ainda não exista.
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
