### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by Thyago-C** [kyriosdata/oo#243]
i) O título sugere que o sistema seja decomposto em módulos. Portanto, a sugestão é de que a decomposição seja feita durante as decisões do design no programa, segundo palavras retiradas do artigo: "The modularizations include the design decisions which must be made before the work on independent modules can begin."

ii) Unified Modeling Language (UML).

iii) Sim, pois a idéia de partes de um todo e de relações entre essas partes remete à orientação a objetos, onde as vantagens são exatamente como descrito nos artigos: fácil manutenção, partes bem definidas e, em caso de problemas, diminuição no escopo de busca, tendo em vista que ao modificar uma parte, as outras partes não sofrem alterações, mas são beneficiadas com a alteração da parte que foi alterada.

**Comment by plinioleitao** [comment]
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
