### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by samirmont0** [kyriosdata/oo#244]
**i.** O título do artigo "decomposing systems into modules" na minha opinião sugere que o sistema não deva ser construído sem dividir ele em partes, ou seja, é necessário que haja essa divisão em módulos, para facilitar o desenvolvimento do mesmo e evitar erros, gerando praticidade para o desenvolvedor.

**ii.** O instrumento usado para documentação é a UML(Unified Modeling Language)

**iii.** É possível perceber claramente ligação com os artigos e a orientação a objetos, uma vez que para boas práticas em OO, deve-se dividir o sistema em partes e usar a documentação/modelagem da UML na sua criação, e é justamente o que está sendo discutido nos textos.

**Comment by plinioleitao** [comment]
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
