### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by rafssn** [kyriosdata/oo#246]
i. No meu entendimento, o significado geral do título de decomposição em módulos se traduz em reduzir problemas grandes e complexos em menores, possivelmente mais simples, no intuito de serem resolvidos de forma mais organizada, a fim de tornar o processo de construção do sistema mais otimizado.

ii. Utilização de UML.

iii. O tema "decompor sistemas em módulos" se encaixa com fortemente com OO, pois a orientação a objetos nos proporciona e dá a possibilidade de descentralizar processos, e dessa forma decompor funcionalidades de um software.

**Comment by plinioleitao** [comment]
OO é um instrumento para decomposição do problema e da solução.
COM APROVEITAMENTO.
