### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by im-pokz** [kyriosdata/oo#247]
i) classe - SIM
ii) objeto - SIM
iii) associação reflexiva - NÃO
iv) agregação - SIM
v) composição - SIM
vi) cardinalidade de associação - NÃO
vii) atributo de classe - SIM
viii) nome de classe - SIM
ix) métodos de classe - SIM
x) pacote (package) - SIM
xi) dependência - SIM
xii) interface (usando círculo) - NÃO
xiii) interface (usando retângulo com indicação de estereótipo) - NÃO
xiv) implementação de interface por uma classe - NÃO
xv) nota - SIM
xvi) associação entre nota e elemento anotado - NÃO
xvii) uso de interface - NÃO
xviii) herança - SIM
xix) classe abstrata - SIM

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Elementos para os quais a resposta foi "não" serão trabalhados posteriormente.
