### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by mantisoficial** [kyriosdata/oo#248]
i) classe - sim;
ii) objeto - sim;
iii) associação reflexiva - sim;
iv) agregação - sim;
v) composição - sim;
vi) cardinalidade de associação - não;
vii) atributo de classe - sim;
viii) nome de classe - sim;
ix) métodos de classe - sim;
x) pacote (package) - sim;
xi) dependência - sim;
xii) interface (usando círculo) - sim;
xiii) interface (usando retângulo com indicação de estereótipo) - sim;
xiv) implementação de interface por uma classe - sim;
xv) nota - não;
xvi) associação entre nota e elemento anotado - não;
xvii) uso de interface - não;
xviii) herança - sim;
xix) classe abstrata - sim;

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Elementos para os quais a resposta foi "não" serão trabalhados posteriormente.
