### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by Thyago-C** [kyriosdata/oo#253]
i. Classe - Sim
ii. Objeto - Sim
iii. Associação reflexiva - Sim
iv. Agregação - Sim
v. Composição - Sim
vi. Cardinalidade de associação - Sim
vii. Atributo de classe - Sim
viii. Nome de classe - Sim
ix. Métodos de classe -Sim
x. Pacote - Sim
xi. Dependência - Sim
xii. Interface (usando círculo) - Sim
xiii. Interface (usando retângulo com indicação de estereótipo) - Sim
xiv. Implementação de interface por uma classe - Sim
xv. Nota - Não
xvi. Associação entre nota e elemento anotado - Não
xvii. Uso de interface - Sim
xviii. Herança - Sim
xix. Classe abstrata - Sim

**Comment by Thyago-C** [comment]
Não entendi muito bem o item xv e xvi. Portanto, considero que não identifiquei os mesmos em UML.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Elementos para os quais a resposta foi "não" serão trabalhados posteriormente. 

A nota é um simples retângulo com "canto dobrado", no qual você deposita texto que explica ou acrescenta informação ao item ao qual está associada. A associação é feita por meio de uma aresta tracejada.
