### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by Moreira-code** [kyriosdata/oo#256]
i. Combinação de propriedades e comportamentos, ou seja, um molde.
ii. Uma classe define um conjunto de métodos, mas são os objetos, entidades "com vida", que podem receber mensagens através da interface definida na classe. ou seja, se existe uma classe Banco, é o objeto cliente que através dos métodos da classe executando por exemplo os métodos da mesma.
iii. Uma associação reflexiva apresenta-se uma classe que relaciona com ela mesma.
iv. Uma classe possui relacionamento com outra classe possuindo instancias das mesmas. ou seja, classe "Pessoa" associada por agregação a classe  "União", por n "prole" e 2 "casamento"
 v. denotado por um losango hachurado, denominasse um todo as partes são criadas a partir deste, de o "todo" não existe, o resto também não.
vi. cardinalidade representada na associação de  0 para 0,1 ou para muitos "*" em vice e versa.
vii. Atributos de classe contidos em baixo do nome da classe, informados pelo tipo e restrição "+" ou "-" ou se é derivado "/"
viii. Em evidencia com a "fonte" maior.
ix. Logo abaixo dos atributos, que fornecem o comportamento dos mesmos, sendo private "+" ou public "-".
x. Denotado por um retângulo com um outro no canto superior esquerdo, dividindo classes em subconjuntos.
xi. representa de forma tracejada representando uma especificação ou implementação da outra.,
xii. representado por um circulo entre associação de classes que identifica a interface.
xiii. Possui o estereótipo "<<Interface>>" indicando como a notação da classe é implementada.
xiv. classe que depende de e uma classe que implementa uma interface, normamelmente 2 classes associados com interface (usando circulo)
xv. Nem tudo pode ser definido em uma linguagem de modelagem, sem importar o quanto extensa ela seja. Para permitir adicionar informações a um modelo não poderia ser representado de outra forma, UML provê a capacidade de adicionar Notas. Uma Nota pode ser colocada em qualquer lugar em um diagrama, e pode conter qualquer tipo de informação, representado por "folha com 1 ponta dobrada" com uma espécia de associação tracejada.
xvi. uma especie de associação tracejada.
xvii. associação tracejada com uma uma seta "apontando".
xviii. representa uma classe com associação apontando para a classe "pai" da herança, sendo praticamente explicito os atributos "compartilhados".
xix. classes com instancias indiretas através da criaçao de objetos de classes derivadas.

**Comment by kyriosdata** [comment]
Muito bom. COM APROVEITAMENTO. 👍
