### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by atilaufg** [kyriosdata/oo#257]
1 - classe: Sim
2 - objeto: Sim
3 - associação reflexiva: Sim
4 - agregação: Sim
5 - composição: Sim
6 - cardinalidade de associação: Sim
7 - atributo de classe: Sim
8 - nome de classe: Sim
9 - métodos de classe: Sim
10 - pacote (package): Sim
11 - dependência: Sim
12 - interface (usando círculo): Sim
13 - interface (usando retângulo com indicação de estereótipo): 
14 - implementação de interface por uma classe
nota: Sim
15 - associação entre nota e elemento anotado: Não
16 - uso de interface: Sim
17 - herança: Sim
18 - classe abstrata: Sim

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Elementos para os quais a resposta foi "não" serão trabalhados posteriormente. No seu caso, aparentemente, apenas um (um ficou sem resposta).
