### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by valeriateles** [kyriosdata/oo#259]
Tenho grande dificuldade em programação, mas acredito que em pouco tempo e com dedicação devo conseguir.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Essa visão é importante. Vamos precisar dessa atitude. Dado que "programação" propriamente dita é assunto de outra disciplina, você precisa iniciar esforço específico. Eu e o Prof. Plínio (@plinioleitao) vamos te ajudar. A sugestão é você localizar um livro, portal ou outro, pertinente à programação Java e dedique uma parte do seu tempo, provavelmente diariamente, para que possa adquirir habilidades de programação. O que me diz?
