### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by SleepyDarlin** [kyriosdata/oo#260]
i. classe: sim
ii. objeto: sim
iii. associação reflexiva: sim
iv. agregação: sim
v. composição: sim
vi. cardinalidade de associação: sim
vii. atributo de classe: sim
viii. nome de classe: sim
ix. métodos de classe: não 
x. pacote (package): sim
xi. dependência: sim
xii. interface (usando círculo): sim
xiii. interface (usando retângulo com indicação de estereótipo): sim
xiv. implementação de interface por uma classe: não 
xv. nota: não
xvi. associação entre nota e elemento anotado: não
xvii. uso de interface: sim
xviii. herança: sim
xix. classe abstrata: não

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Elementos para os quais a resposta foi "não" serão trabalhados posteriormente.
