### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by pablofurtado** [kyriosdata/oo#261]
i. classe: Sim
ii. objeto: Sim
iii. associação reflexiva: Sim
iv. agregação: Sim
v. composição: Sim
vi. cardinalidade de associação: Sim
vii. atributo de classe: Sim
viii. nome de classe: Sim
ix. métodos de classe: Sim
x. pacote (package): Sim
xi. dependência: Sim
xii. interface (usando círculo): Sim
xiii. interface (usando retângulo com indicação de estereótipo): Sim
xiv. implementação de interface por uma classe: Sim
xv. nota: Não
xvi. associação entre nota e elemento anotado: Não
xvii. uso de interface: Sim
xviii. herança: Sim
xix. classe abstrata: Sim

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍 
Elementos para os quais a resposta foi "não" serão trabalhados posteriormente.
