### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by andrey-dias** [kyriosdata/oo#262]
1 classe sim
2 objeto sim
3 associação reflexiva não
4 agregação não
5 composição sim
6 cardinalidade de associação não
7 atributo de classe sim
8 nome de classe sim
9 métodos de classe sim
10 pacote (package) sim
11 dependência sim
12 interface (usando círculo) não
13 interface (usando retângulo com indicação de estereótipo) sim
14 implementação de interface por uma classe sim
15 nota sim
16 associação entre nota e elemento anotado não
17 uso de interface sim 
18 herança sim
19 classe abstrata sim

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
