### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by samirmont0** [kyriosdata/oo#265]
i. Classe: Sim
ii. Objeto: Sim
iii. Associação reflexiva: Sim
iv. Agregação: Sim
v. Composição: Sim
vi. Cardinalidade de associação: Sim
vii. Atributo de classe: Sim
viii. Nome de classe: Sim
ix. Métodos de classe: Sim
x. Pacote (package): Sim
xi. Dependência: Sim
xii. Interface (usando círculo): Sim
xiii. Interface (usando retângulo com indicação de estereótipo): Sim
xiv. Implementação de interface por uma classe: Sim
xv. Nota: Não
xvi. Associação entre nota e elemento anotado: Não
xvii. Uso de interface: Sim
xviii. Herança: Sim
xix. Classe abstrata: Sim

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
