### ISSUE TITLE
 "OO"

### ISSUE THREAD

**Issue by taynasantana** [kyriosdata/oo#268]
1-classe= sim
2-objeto= sim
3-associação reflexiva= não
4-agregação= sim
5-composição= sim
6-cardinalidade de associação= não
7-atributo de classe= sim
8-nome de classe= sim
9-métodos de classe= sim
10-pacote (package)= sim
11-dependência= sim
12-interface (usando círculo)= não
13-interface (usando retângulo com indicação de estereótipo)= não
14-implementação de interface por uma classe= não
15-nota= não
16-associação entre nota e elemento anotado= não
17-uso de interface= não
18-herança= sim
19classe abstrata= sim

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
