### ISSUE TITLE
Minhas dúvidas

### ISSUE THREAD

**Issue by jeferson1f** [kyriosdata/oo#27]
1. Iremos aprender apenas conceitos ou vamos desenvolver códigos em linguagens de programação orientadas a objetos?
2. A matéria utilizará provas práticas com provas online em plataformas como o Shariff Judge ou serão apenas trabalhos?

**Comment by kyriosdata** [comment]
Primeira. Vamos aprender conceitos, mas não são suficientes. Precisamos compreendê-los e, isto será obtido por meio de atividades práticas. Os conceitos apenas podem ser obtidos em inúmeras fontes e "são simples", aplicá-los adequadmente, por outro lado, é uma atividade bem mais exigente. A aplicação dá origem a modelos. Tenho que reiterar, quando se aplica orientação a objetos, primeiro você produz **modelos orientados a objetos**. Na sequência, você os implementa em alguma linguagem de programação. Quando se programa de forma orientada a objetos, ou programação orientada a objetos, a programação é muito importante, não se questiona, contudo, o modelo orientado a objetos é ainda mais. Tanto que a programação, neste contexto, pode ser tratada melhor como uma "tradução" para a linguagem em questão. Se é uma linguagem que oferece "recursos orientados a objetos", a tradução é mais simples, caso contrário, terá mais dificuldades. Finalmente, dito tudo isto, também teremos programação. Talvez o @plinioleitao queira acrescentar algo aqui. 

Segunda. Não está prevista avaliação nas plataformas que citou. Todas as nossas avaliações serão realizadas por meio do Github (nossa plataforma). As nossas atividades, entendo, são todas "práticas". 

COM APROVEITAMENTO. 👍
