### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by pavaladao** [kyriosdata/oo#270]
i.classe - sim
ii.objeto - sim
iii.associação reflexiva - sim
iv.agregação- sim
v.composição- sim
vi.cardinalidade de associação- nao
vii.atributo de classe - sim
viii.nome de classe - sim
ix.métodos de classe - sim
x.pacote (package) - nao
xi.dependência - sim
xii.interface (usando círculo) - nao
xiii.interface (usando retângulo com indicação de estereótipo) - sim
xiv.implementação de interface por uma classe - nao
xv.nota - nao
xvi.associação entre nota e elemento anotado - nao
xvii.uso de interface - nao
xviii.herança - sim
xix.classe abstrata - sim

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
