### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by pavaladao** [kyriosdata/oo#271]
Sim estou apto a implementar esses diagramas em linguagem php.

**Comment by kyriosdata** [comment]
Ótimo, contudo, lembro que estaremos utilizando a linguagem Java, na disciplina. Várias outras disciplinas do curso estarão empregando Java. Não seria o caso de iniciar um trabalho com Java. Estamos aqui para ajudar.

COM APROVEITAMENTO. :+1:
