### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by driellyg** [kyriosdata/oo#278]
Não possuo muito conhecimento em Java, seria necessário consultar uma fonte de informação para aprender. Acredito que em linguagem C eu consiga realizar, mesmo sem consulta.

**Comment by kyriosdata** [comment]
Observe que a linguagem C não oferece construções para implementar, por exemplo, herança. Isso tornaria muito onerosa a implementação em C, eu diria que é simplesmente inviável. Minha sugestão é iniciar esforço para ambientação com Java. Estamos aqui para ajudar. 

COM APROVEITAMENTO. :+1:
