### ISSUE TITLE
 "Java" 

### ISSUE THREAD

**Issue by taynasantana** [kyriosdata/oo#279]
Em Java eu não conseguiria, mesmo usando consulta ,  pois nunca usei essa linguagem. Talvez consiga em linguagem C.

**Comment by kyriosdata** [comment]
A linguagem C não oferece suporte para conceitos como herança e polimorfismo. Ou seja, implementá-los em C seria uma tarefa "muito" onerosa. Não é viável. Sugiro que inicie sua ambientação com Java. Procure uma fonte que agrade e comece a trabalhar. Recursos simples como os ilustrados. Estamos aqui para ajudar, inclusive nessa ambientação. 

COM APROVEITAMENTO. :+1:
