### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by atilaufg** [kyriosdata/oo#280]
Apesar de ter 1 ano que não programo nada, acho que conseguiria em C, mas consultando a internet ou até mesmo os mapeamentos em Java que você passou, da pra ter uma noção de como fazer em Java.

**Comment by kyriosdata** [comment]
Ótimo! A implementação em C, contudo, seria "exigente". Observe que não temos recursos em C para diretamente implementar, por exemplo, polimorfismo. Seria apenas trabalhose. Não é a linguagem recomendada para o nosso caso. 

COM APROVEITAMENTO. :+1:
