### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by MatheusPe** [kyriosdata/oo#283]
i. Lápis Faber Castel da classe lápis
Fone de ouvido Samsung da classe fone de ouvido
Notebook Del da classe Notebook.

ii. porta branca da classe Porta
parede verde da classe Parede
telhado de telhas da classe Telhado

iii. torcedor alto da classe Torcedor
torcedor baixo da classe Torcedor
torcedor rico da classe Torcedor

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
