### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by MatheusPe** [kyriosdata/oo#284]
i.classe - Reconheço
ii.objeto - Reconheço
iii.associação reflexiva - Reconheço
iv.agregação - Reconheço
v.composição - Reconheço
vi.cardinalidade de associação - Não reconheço
vii.atributo de classe - Reconheço
viii.nome de classe - Reconheço
ix.métodos de classe - Reconheço
x.pacote (package) - Não reconheço
xi.dependência - Reconheço
xii.interface (usando círculo) - Reconheço
xiii.interface (usando retângulo com indicação de estereótipo) - Reconheço
xiv.implementação de interface por uma classe - Não reconheço
xv.nota - Não reconheço
xvi.associação entre nota e elemento anotado - Não reconheço
xvii.uso de interface - Não reconheço
xviii.herança - Reconheço
xix.classe abstrata - Não reconheço

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
