### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by driellyg** [kyriosdata/oo#295]
Professor, qual o link das aulas síncronas? Tento acessar pelo link disponibilizado mas recebo um pop up dizendo que não foi possível ingressar na reunião.

**Comment by plinioleitao** [comment]
Conforme posto no Ambiente SIGAA da disciplina, a nossa página, a nossa referência, o nosso ambiente virtual da aprendizagem é o Github, especificamente o repositório : https://github.com/kyriosdata/oo 

No link acima você irá ler: "Os momentos síncronos ocorrerão na sala **virtual** das 19h às 20h, toda terça-feira". 
Clique na palavra "virtual" para ter acesso à sala virtual.

Importante: você precisa estar "logada" no seu e-mail institucional (domínio discente.ufg.br). (@kyriosdata pode comentar aqui)
