### ISSUE TITLE
Duvidas A02.1

### ISSUE THREAD

**Issue by MMHIT** [kyriosdata/oo#300]
Uma dúvida que surgiu na leitura do material, quanto ao que é oo.

Poderíamos definir oo como uma forma de fragmentar a realidade em versões menores dela mesma?
ou mesmo dizer que ela é a forma utilizada com a qual podemos descrever / detalhar a composição de uma parte da realidade?

**Comment by plinioleitao** [comment]
Em nosso contexto, a abstração OO é uma maneira para modelar (construir um modelo para) um problema ou a solução de um problema. A divisão em pedaços (ou fragmentação, conforme você mencionou) é um dos recursos empregados, mas a abstração OO aplica vários 'conceitos', tais como classe, objeto, associação, herança, dentre outros (@kyriosdata pode comentar aqui).
COM APROVEITAMENTO.
