### ISSUE TITLE
Reflexão A02.1

### ISSUE THREAD

**Issue by MMHIT** [kyriosdata/oo#301]
Dentro de suas diferênças de paradigma, o ganho se localiza na abstração e na manutenção da estrutura construída.
As vantagens de se enchergar o C++ com OO, fazem com que C seja simples e engessado demais.
Em resumo, sua vantagem é ser mais abrangente quanto as possibilidades de construção.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ (em relação ao código em C) é a representação da abstração OO diretamente no código, com consequentes benefícios para posterior manutenção do código.
Por favor, prefira a palavra 'enxergar'.
COM APROVEITAMENTO.
