### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by wevertoum** [kyriosdata/oo#328]
i. Classe - Sim
ii. Objeto - Sim
iii. Associação reflexiva - Sim
iv. Agregação - Sim
v. Composição - Sim
vi. Cardinalidade de associação - Não
vii. Atributo de classe - Sim
viii. Nome de classe - Sim
ix. Métodos de classe -Sim
x. Pacote - Sim
xi. Dependência - Sim
xii. Interface (usando círculo) - Sim
xiii. Interface (usando retângulo com indicação de estereótipo) - Não
xiv. Implementação de interface por uma classe - Sim
xv. Nota - Não
xvi. Associação entre nota e elemento anotado - Não
xvii. Uso de interface - Sim
xviii. Herança - Sim
xix. Classe abstrata - Sim

**Comment by wevertoum** [comment]
Mais uma vez peço desculpa pelo atraso, estou com muitos problemas sem internet em casa, não sei se ainda adiante, estou apenas tentando, amanhã tiro duvidas na nossa reunião

**Comment by kyriosdata** [comment]
Lembro que o prazo é importante e que um espaço significativo de tempo está sendo dado para que os exercícios sejam realizados. Também estamos atentos para exigir um "quantidade pequena" de acesso a internet, intencionalmente, para amenizar tais situações. 

COM APROVEITAMENTO. 👍
