### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by wevertoum** [kyriosdata/oo#329]
Em Java eu não conseguiria no momento, mas estou estudando e relembrando alguns pontos da sintaxe pra adequar ao paradigma da matéria, estou a vários meses trabalhando apenas com paradigma funcional em typescript, conseguiria em typescript.

**Comment by plinioleitao** [comment]
O prazo para a entrega da tarefa expirou em 21/09/2020 (@kyriosdata pode comentar).
SEM APROVEITAMENTO.

**Comment by kyriosdata** [comment]
Temos um prazo estabelecido para as atividades, em boa parte dos casos, estabelecido com significativa antecedência, até para acomodar eventuais empecilhos. Contudo, se deixar para o último momento, pode não ser suficiente. Observe que para esta atividade são apenas duas linhas. Estamos reconsiderando o resultado e reiterando a necessidade de eliminar obstáculos que possam impedir o seu aproveitamento na disciplina. Caso considere apropriado, entre em contato com a coordenadora do curso para alguma explanação adicional, se entender que os atrasos tendem a ser recorrentes. 

COM APROVEITAMENTO. 👍
