### ISSUE TITLE
08

### ISSUE THREAD

**Issue by wevertoum** [kyriosdata/oo#330]
Minha duvida é se é a partir desses conceitos que temos aqueles pontos do tipo _many to many_ (várias relações), eu vejo meus colegas do back-end citando isso mas não sei bem se esse conceito vem da relação entre classes do POO ou de algum conceito de banco de dados

**Comment by plinioleitao** [comment]
Para responder precisamente o seu comentário, seria necessário conhecer em qual contexto os seus 'colegas do back-end' fazem suas citações. Independente disso, na nossa disciplina introduzimos uma representação da abstração OO por meio de classes que possuem associações entre si. 
Note que o termo 'muitos-para-muitos' é empregado em vários 'contextos da computação', tais como redes de computadores, banco de dados, abstração OO, dentre outros. Definitivamente, não estamos tratando diretamente sobre 'design de banco de dados' em nossa disciplina.
SEM APROVEITAMENTO, pois expirou o período para a atividade: até 26/09/2020 (@kyriosdata pode comentar aqui).
