### ISSUE TITLE
Estruturas T03

### ISSUE THREAD

**Issue by MMHIT** [kyriosdata/oo#357]
i. O título sugere na verdade a fragmentação do problema em partes menores, tratar uma situação por suas partes atômicas, onde o todo, se subdividido, atua como uma composição de pequenos problemas e não um único grande problema.

ii. A ferramenta usada para documentação é o GitHub.

iii.Sim, A relação existente está na abordagem, nos artigos a mensão a fragmentação e documentação de um sistema ou software transparecem a relação de orientação a objetos, onde o conceito de OO presupõe essa forma de pensamento, modularizar e especificar são as chaves indicadas por eles.

**Comment by kyriosdata** [comment]
- Não sei se o termo "atômico" aqui é apropriado, pois pode passar uma ideia de atomicidade, o que não é o caso. 
- Melhor é "menção" em vez de mensão [sic]. 

Em atividades posteriores, vamos ficar atentos aos prazos. Eles são estabelecidos com devida antecedência para permitir que situações excepcionais possam ser contempladas. Neste caso, tivemos mais de duas semanas de atraso. A atenção ao prazo é imprescindível para obter o aproveitamento esperado. Caso esteja vivenciando uma situação peculiar e que mereça a atenção da coordenadora do curso, visando o seu aproveitamento na disciplina, por favor, faça com que ela saiba para que possamos contemplar esta eventual especificidade. 

COM APROVEITAMENTO. 👍
