### ISSUE TITLE
Fundamentos T04

### ISSUE THREAD

**Issue by MMHIT** [kyriosdata/oo#358]
i. Mais complexos: 39, 40 e 41.

ii. Mais Simples: 31, 34 e 36.

**Comment by kyriosdata** [comment]
Considerando o atraso significativo na entrega dos trabalhos, este é um outro exemplo, sugiro que entre em contato com a coordenadora do curso, principalmente se o motivo do atraso persistir, impedindo que você entregue os trabalhos no prazo estipulado. 

COM APROVEITAMENTO. 👍
