### ISSUE TITLE
Classificação T05

### ISSUE THREAD

**Issue by MMHIT** [kyriosdata/oo#374]
i. "Tablete","Smatphone","Notebook","Máquina Fotográfica", "Mesa digitalizadora" da classe "Digitais"
   "Caderno", "Lápis", "Caneta" da classe "Analógicos"
   "Camiseta", "óculos", "Mochila" da classe "Vestíveis"

ii. "tijolos", "janelas", "portas","Telhado" da classe "construção"
   "Sofá", "mesa", "Cadeiras", "cama" da classe "mobilha"
   "Quadros", "cortinas", "Papel de parede" da classe "Decoração"

iii. "Atacante", "Centro-Avante", "Goleiro" da classe "Jogadores"
    "Arquibancada", "Campo", "Vestiários" da classe "Estádio"
    "bandeirinhas", "Juízes" da classe "Equipe técnica"

**Comment by kyriosdata** [comment]
A resposta está correta, mas segue bem após o prazo estipulado para a realização. Em geral, este prazo é estabelecido com sensível período para admitir contemplar situações excepcionais. Ou seja, fique atento para que obtenha aproveitamento. 

COM APROVEITAMENTO. 👍
