### ISSUE TITLE
Java T07

### ISSUE THREAD

**Issue by MMHIT** [kyriosdata/oo#470]
i. Consegue implementar os "diagramas" ilustrados nestes mapeamentos, seja em Java ou em outra linguagem de programação, mesmo que seja necessário realizar consulta a alguma fonte de informação?
                    Resposta: Sim, consigo.

Noutras palavras, está apto, mesmo com consulta, a criar uma simples classe Sapato, em Java, sem atributos e métodos, por exemplo?
                    Resposta: Sim, estou.
                           public class Sapato {}

Ou em outra linguagem de programação?
                  Resposta: Sim, estou.

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
