### ISSUE TITLE
Minhas dúvidas

### ISSUE THREAD

**Issue by FerreiraRaphael** [kyriosdata/oo#50]
Como vai funcionar as avaliações? 
Quantos tópicos teremos?
Como vai funcionar as presenças?

**Comment by plinioleitao** [comment]
Sobre as presenças e as notas (avaliações), veja o plano da disciplina no link: https://github.com/kyriosdata/oo/blob/master/media/plano-poo.pdf
O número de tópicos será definido no decorrer do curso da disciplina.

**Comment by FerreiraRaphael** [comment]
👍

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
