### ISSUE TITLE
Minhas dúvidas

### ISSUE THREAD

**Issue by atilaufg** [kyriosdata/oo#65]
Não tenho nenhuma dúvida ate o momento.

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.

**Comment by atilaufg** [comment]
Professor, percebi que não criei o repertorio com o nome ''poo-2020-01'' como você pediu, posso criar outro com este nome e anexar na issue Repertório?

**Comment by plinioleitao** [comment]
Você pode renomear o repositório clicando em 'Settings'. 
Se você renomear o repositório, favor criar (nova) issue para nos informar sobre o novo nome (@kyriosdata).
