### ISSUE TITLE
Dúvidas sobre Contexto

### ISSUE THREAD

**Issue by felipekafuri** [kyriosdata/oo#66]
Bom dia professores, minha duvida é que, eu não entendi muito bem a definição de problema.

**Comment by kyriosdata** [comment]
Em geral, há uma dicotomia entre problema e solução. Ou entre o que se deseja resolver e a resolução correspondente. No domínio de software, o problema, em geral, se refere ao "domínio" do cliente, ao negócio da empresa em questão e, em particular, a algum ponto específico que causa certa "dor", "incômodo". O cliente possui alguma "queixa", "reclamação" que deseja ver "resolvida" ou "eliminada". Esta é a língua portuguesa e como a usamos associadas à problema e à solução neste escopo específico. 

O que me diz?

**Comment by felipekafuri** [comment]
Agora sim entendi! obrigado professor
