### ISSUE TITLE
Dúvidas sobre Contexto

### ISSUE THREAD

**Issue by SleepyDarlin** [kyriosdata/oo#71]
Bom dia professores, a minha dúvida é a seguinte:
Reparei que tem linhas de código em Java no contexto, tendo em vista que eu ainda não estudei sobre Java, teremos aulas para aprender sobre ou isso é irrelevante por enquanto?

**Comment by kyriosdata** [comment]
Gustavo, desconheço o tópico pertinente, estou tratando como dúvida pessoal sua. (@plinioleitao)

Não há nenhum código em Java fornecido até o momento, exceto em alguns slides. Não há previsão de aula sobre a linguagem Java. Dado que desconhece e, provavelmente terá que fazer uso desta linguagem de programação ao longo do curso, sugiro que inicie o seu estudo desta linguagem em particular. Inclusive os exemplos na disciplina serão feitos empregando tal linguagem. Em tempo, o ideal seria o emprego de alguma linguagem orientada a objetos, você conhece alguma?
