### ISSUE TITLE
Meu repositório

### ISSUE THREAD

**Issue by Thiago-V-A** [kyriosdata/oo#778]
Meu nome: Thiago Vicente de Aquino
Meu registro acadêmico: 202201716
Minha conta no Github: https://github.com/Thiago-V-A/poo-2023-01

**Comment by kyriosdata** [comment]
Olá Thiago, neste caso específico, não seria apropriado você fechar a issue, suponho, pois o responsável não iria mais considerar este conteúdo. Contudo, missão cumprida.
