### ISSUE TITLE
Meu repositório

### ISSUE THREAD

**Issue by CaioxDias** [kyriosdata/oo#786]
Caio Barbosa Dias
Matrícula: 202108693
https://github.com/CaioxDias/poo-2023-01
Quais são os softwares que são os mais recomendados para a disciplina?

**Comment by kyriosdata** [comment]
Caio, este não seria o contexto adequado para a sua pergunta. A pergunta é bem-vinda, mas a _issue_ em questão tem um foco bem definido. Neste caso, você deveria simplesmente responder e não acrescentar esta pergunta. Em tempo, faça a pergunta na aula de hoje.
