### ISSUE TITLE
Minhas dúvidas

### ISSUE THREAD

**Issue by MMHIT** [kyriosdata/oo#81]
Prezado professor,
Não foi possível por questões técnicas assistir
a aula do dia 01/09.
Portanto minha dúvida é, o que foi passado a aula e
qual a senha para ingressar na disciplina da plataforma turing?

**Comment by plinioleitao** [comment]
Todas as postagens da disciplina estão no GitHub, então não será utilizada a plataforma Turing.
O conteúdo de todas as aulas estão na forma de Tópicos, conforme postado no GitHub.

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
