### ISSUE TITLE
João Gabriel Tavares Félix Monteiro

### ISSUE THREAD

**Issue by JohnTFM** [kyriosdata/oo#832]
https://github.com/JohnTFM
SIM

**Comment by kyriosdata** [comment]
Está fora do prazo, mas vamos em frente.

**Comment by kyriosdata** [comment]
Também está fora do padrão requisitado. Você deve criar o repositório ds-2023-02. Por favor, continuo aguardando.

**Comment by JoaoUFG** [comment]
https://github.com/JoaoUFG
havia colocado o link do meu outro repositório, me desculpe!
