### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by schloegl10** [kyriosdata/oo#84]
A programação pode ser feita de inúmeras formas e paradigmas. Podendo em cada projeto escolher a que se pensa mais proveitosa. Contudo existem muitos projetos que poderiam usar duas ou mais paradigmas de forma eficiente, devendo apenas levar em conta os pontos fortes de um em comparação com dos outros. Essa visão de paradigma influencia também a escolha da linguagem, já que cada uma costuma ter um paradigma na qual é baseado. Um exemplo é C++ que é baseado na orientação a objeto e C que é orientado na programação procedural.
    A programação orientada a objetos tem como estrutura criar métodos e classes que simbolizem os acontecimentos e padrões do mundo real, dessa forma facilitando o entendimento do código durante manutenções e remodelações. A programação procedural visa criar procedimentos isolados que possam ser chamados por todo o programa (incluindo eles mesmos), permitindo assim reutilização do código. 
    Existem vários pontos na qual C++ se destaca com relação ao C e o mesmo pode ser dito no sentido contrário. Ao trabalhar com C++ em comparação ao C, temos a vantagem de ainda trabalhar com uma linguagem que apresenta velocidade, funções de baixo nível e programação procedural. Alem desses pontos em comum, C++ permite a criação de classes para realizar a orientação a objeto, segurança maior, compatibilidade com outras linguagens, uma facilidade maior de programar e funcionalidades que não existem no C (string, classes, enum, restringir acesso a variáveis, ...). Um exemplo de preferencia por C++ é na programação de jogos, que permite uma linguagem rápida e leve, enquanto possibilita funcionalidades que tornam a criação de tais projetos mais acessível e menos dispendiosa. O uso de OO também torna o código de mais fácil entendimento quando trabalhando com equipes grandes e projetos maiores.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
