### ISSUE TITLE
Estruturas

### ISSUE THREAD

**Issue by schloegl10** [kyriosdata/oo#85]
1. A decomposição de um sistema durante sua fase inicial de desenvolvimento tem em mente a análise de requisitos. Tal processo visa compreender e estruturar as partes principais, assim como o que será realizado em cada uma. Dessa forma ao se criar uma boa documentação de como o programa deve funcionar é possível realizar as modularizações do mesmo. Já que apesar de não existir o programa, o mesmo foi idealizado e estruturado durante sua concepção.

2. Na disciplina o instrumento usado para documentar é o UML (Unified Modelling Language), uma linguagem usada para visualizar, especificar, construir e documentar softwares complexos

3. A relação dos textos com OO é que assim como tanto enfatizado nos mesmo, OO também necessita de modularizar e dividir o programa em partes menores. No caso dos textos foi utilizado diversas metodologias para realizar as divisões do programa, em OO é utilizado a analise e criação de objetos e classes que representem artefatos do mundo real presente do programa, permitindo melhor leitura, divisão e compreensão.

**Comment by kyriosdata** [comment]
Observação sobre (i). Quando se "divide" na fase de análise, o foco está na "compreensão" do problema. Naturalmente, pode interferir na posterior fase de _design_, quando uma proposta para o software é produzida. Contudo, vale ressaltar que estas fases são independentes e, ao menos conceitualmente, na definição formal, não se deve tomar decisões de projeto (_design_) na fase de requisitos, ok? (@plinioleitao)

Muito bom. COM APROVEITAMENTO. 👍
