### ISSUE TITLE
Classificação

### ISSUE THREAD

**Issue by schloegl10** [kyriosdata/oo#86]
1.  1. Objeto "Aplicativo Instragram" da classe "Aplicativos"
     2. Objeto "Camisa pequena da marca SVPERBIA" da classe "Camisa"
     3. Objeto "Lente Canon EF-S 17-55mm f/2.8 IS USMPreto" da classe "Lentes"

2.  1. Objeto "Tinta Verde" da classe "Tinta"
     2. Objeto "Porta Branca" da classe "Porta"
     3. Objeto "Telha Marrom" da classe "Telha"

3.  1. Objeto "Grama Bermuda ou esmeralda" da classe "Grama"
     2. Objeto "Propaganda MasterCard" da classe "Propaganda"
     3. Objeto "Estádio de futebol" da classe "Estádio"

**Comment by kyriosdata** [comment]
Observação: em geral, a classe ou categoria é no singular. Observe que uma classe ou categoria não tem a proposta de "reunir" as instâncias da coleção à qual se refere, ok? Ou seja, é melhor Aplicativo e Lente. 

Muito bom. COM APROVEITAMENTO. 👍
