### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by AlvesMarina** [kyriosdata/oo#88]
Visto que OO é uma ferramenta e uma forma diferente de ver uma coisa já existente, o que se ganha com código C++ em relação ao C é agilidade, praticidade, tempo e otimização na hora de desenvolver o código. O código C++ apresenta ferramentas diferentes das do código C e essas ferramentas são usadas para agilizar e otimizar o desenvolvimento do software, comparado à linguagem C. Ferramentas mais práticas e funcionais facilitam o desenvolvimento do software, dando assim tempo e possibilidade para o desenvolvedor aprimorar e otimiza-lo, a fim de melhorar o produto final.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
