### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by calebesz** [kyriosdata/oo#90]
OO é uma forma de ver as coisas, portanto o C++ que é orientado a objetos é mais flexivel para a programação em relação ao C, entende-se que o C++ é uma versão melhorada, e com mais recursos e possibilidades para o programador. Sendo assim em C++ pode-se tanto programar códigos orientados a procedimentos quanto orientados a objetos.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
