### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by mantisoficial** [kyriosdata/oo#92]
Após a leitura do documento e mais algumas pesquisas, conclui que existem sim algumas vantagens na utilização de OO.  Um código escrito baseado em OO é mais confiável, reutilizável e mais fácil de manter. A programação orientada a objetos é uma ferramenta mais flexível que a programação estruturada mas continua sendo apenas uma ferramenta. No final o programador que escolhe qual método utilizar.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
