### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by MateSilver** [kyriosdata/oo#93]
A oo (orientação à objetos) é um método de construção de algoritmo, do qual um problema é resolvido criando um objeto  abstrato, usando pra resolução do algoritmo.  É um método a ser ultilizado para simplificar problemas complexos, agrupando características e processos em um objeto. Porém seu uso é relativo, ou seja, não simplifica todos os problemas e seu uso deve ser moderado, de forma que algoritmos em c++, onde se pode usar oo e outros recursos, necessariamente não são melhores que algoritmos em c como um todo. C++ e oo devem ser escolhidos com base no que se irá desenvolver. Caso o algoritmo a ser ultilizado permite uma orientação a objetos, vale o uso de C++, onde se pode implementar oo diretamente.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
