### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by Lapot300** [kyriosdata/oo#97]
Pode-se empregar OO para registrar qualquer recorte do universo, seja um problema ou uma solução proposta, ou uma ideia. Na Engenharia de Software, tanto requisitos, quando design e implementação podem empregar OO. Porém seu uso é relativo, ou seja, não simplifica todos os problemas e seu uso deve ser moderado, de forma que algoritmos em c++, onde se pode usar OO e outros recursos, necessariamente não são melhores que algoritmos em c como um todo. Um código escrito baseado em OO é mais confiável, reutilizável e mais fácil de manter. Por isso  caso o algoritmo a ser utilizado permite uma orientação a objetos, vale o uso de C++. Mas no final o programador que escolhe qual linguagem utilizar.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
