### ISSUE TITLE
Reflexão

### ISSUE THREAD

**Issue by HenriqueMartinsCosta** [kyriosdata/oo#99]
Fazer com código orientado a objetos ou não é uma questão similar à da recursividade ou iteratividade. Qualquer função iterativa pode ser feita de forma recursiva e qualquer função recursiva pode ser feita de forma iterativa, apesar de cada uma ter seus pros e contras. A iteratividade proporciona um melhor desempenho, e a recursividade confere ao código maior legibilidade, mas o que realmente influencia a escolha de uma ou outra é a decisão do programador. O mesmo se aplica à OO, ela é uma forma de fazer o código, aumentando sua legibilidade e intuitividade, ela não é melhor ou pior, é uma escolha determinada pela necessidade ou vontade do programador.

**Comment by plinioleitao** [comment]
O que supostamente se ganha com código em C++ em relação ao código em C? A abstração OO é representada diretamente no código, com consequentes benefícios para posterior manutenção do código. 
COM APROVEITAMENTO.
